AmberOnBoard: MsgHub Class Reference
MsgHub Class Reference
Message instances for inter-module and module-child communication.
#include <MsgHub.h>
Public Member Functions
virtual ~MsgHub ()
Destructor.
void attachObserverToMsg (Observer *observer, int type)
Attaches observer to message type.
void detachObserverFromMsg (Observer *observer, int type)
Detaches observer from message type.
void notifyObservers (int type)
Notifies observers about new message.
shared_ptr< Message_M2M > getMsg (Observer *)
Returns the oldest message for observer.
int getMsgCount (Observer *)
Returns the number of messages left for observer.
void appendMsg (shared_ptr< Message_M2M > message)
Appends a new message to the hub.
Static Public Member Functions
static MsgHub * getInstance ()
Implements getInstance() of Singleton pattern.
Private Member Functions
MsgHub ()
Constructor.
Private Attributes
unordered_map< int,
unordered_set< Observer * > > map_MsgType_ObsList
unordered_map< Observer
*, queue< shared_ptr
< Message_M2M > > * > map_Obs_MsgList
unordered_map< shared_ptr
< Message_M2M >, int > map_Msg_ObsCount
unordered_map< Observer
*, mutex * > map_Obs_Mutex
mutex mutex_MsgType_ObsList
mutex mutex_Obs_MsgList
mutex mutex_Msg_ObsCount
mutex mutex_Obs_Mutex
Static Private Attributes
static MsgHub * instance = 0
Detailed Description
Message instances for inter-module and module-child communication.
Message Hub for inter-module communication.
Message handling for inter-module communication.
Classes of type message just hold the data necessary for inter-module and module-child communication as ValContainer.
Author
Daniel Wagenknecht
Version
2014-10-31
This class handles the communication between modules. A Module instance could register for a certain message id and gets notified as soon as there are pending message on the hub. Implements mediator pattern, singleton and observable.
Author
Daniel Wagenknecht
Version
2014-10-31
Class for realizing encapsulated communication of the application modules. Implements Observer pattern for module notification. Implements Singleton pattern for global uniqueness.
Author
Daniel Wagenknecht
Version
2014-10-31
Definition at line 27 of file MsgHub.h.
Constructor & Destructor Documentation
MsgHub::~MsgHub () virtual
Destructor.
Destructor of MsgHub instances.
Definition at line 25 of file MsgHub.cpp.
MsgHub::MsgHub () private
Constructor.
Default Constructor of MsgHub instances.
Definition at line 19 of file MsgHub.cpp.
Referenced by getInstance().
Member Function Documentation
void MsgHub::appendMsg (shared_ptr< Message_M2M > message)
Appends a new message to the hub.
Appends the message specified by 'message' to the hub and notifies all observers for this message type aout a new message.
Parameters
message Pointer to the Message instance.
Definition at line 274 of file MsgHub.cpp.
References map_Msg_ObsCount, map_MsgType_ObsList, map_Obs_MsgList, map_Obs_Mutex, mutex_Msg_ObsCount, mutex_MsgType_ObsList, mutex_Obs_MsgList, mutex_Obs_Mutex, and notifyObservers().
Referenced by ModuleEvent::pollMsgFromChildren(), ModuleNetworking::pollMsgFromChildren(), Module::pollMsgFromHub(), Initializer::setup(), and sig_handler().
void MsgHub::attachObserverToMsg (Observer * observer, int type)
Attaches observer to message type.
Attaches 'observer' to messages with id 'type'. After that operation, the observers update method gets called, each time a new message of this type lies on hub. This method is thread safe.
Parameters
observer The observer instance to attach.
type The message identifier to attach the observer to.
Definition at line 51 of file MsgHub.cpp.
References map_MsgType_ObsList, map_Obs_MsgList, map_Obs_Mutex, mutex_MsgType_ObsList, mutex_Obs_MsgList, and mutex_Obs_Mutex.
Referenced by Initializer::Initializer(), ModuleEvent::ModuleEvent(), ModuleImgProcessing::ModuleImgProcessing(), ModuleIO::ModuleIO(), and ModuleNetworking::ModuleNetworking().
void MsgHub::detachObserverFromMsg (Observer * observer, int type)
Detaches observer from message type.
Detaches 'observer' from messages with id 'type'. After that operation, the observers update method does not get called, each time a new message of this type lies on hub. This method is thread safe.
Parameters
observer The observer instance to detach.
type The message identifier to detach the observer from.
Definition at line 100 of file MsgHub.cpp.
References map_MsgType_ObsList, and mutex_MsgType_ObsList.
MsgHub * MsgHub::getInstance () static
Implements getInstance() of Singleton pattern.
Implements the getInstance()-function required for Singleton pattern.
Returns
Pointer to MsgHub instance.
Definition at line 33 of file MsgHub.cpp.
References instance, and MsgHub().
Referenced by Initializer::Initializer(), ModuleEvent::ModuleEvent(), ModuleImgProcessing::ModuleImgProcessing(), ModuleIO::ModuleIO(), ModuleNetworking::ModuleNetworking(), Module::msgAvailable(), ModuleEvent::pollMsgFromChildren(), ModuleNetworking::pollMsgFromChildren(), Module::pollMsgFromHub(), Module::run(), Initializer::setup(), and sig_handler().
shared_ptr< Message_M2M > MsgHub::getMsg (Observer * observer)
Returns the oldest message for observer.
Returns the oldest pending message for 'observer'.
Parameters
observer The observer for which the message is pending.
Returns
Message for the observer.
Definition at line 155 of file MsgHub.cpp.
References map_Msg_ObsCount, map_Obs_MsgList, map_Obs_Mutex, mutex_Msg_ObsCount, mutex_Obs_MsgList, and mutex_Obs_Mutex.
Referenced by Module::pollMsgFromHub().
int MsgHub::getMsgCount (Observer * observer)
Returns the number of messages left for observer.
Returns the number of pending messages in the queue of observer 'observer'.
Parameters
moduleID The id of the module to look up message list for.
Definition at line 232 of file MsgHub.cpp.
References map_Obs_MsgList, map_Obs_Mutex, mutex_Obs_MsgList, and mutex_Obs_Mutex.
Referenced by Module::msgAvailable().
void MsgHub::notifyObservers (int type)
Notifies observers about new message.
Notifies all observers of message type 'type' that there are new messages pending This method is thread safe.
Parameters
type The type to notify the observers for.
Definition at line 125 of file MsgHub.cpp.
References map_MsgType_ObsList, and mutex_MsgType_ObsList.
Referenced by appendMsg().
Member Data Documentation
MsgHub * MsgHub::instance = 0 static private
Definition at line 44 of file MsgHub.h.
Referenced by getInstance().
unordered_map<shared_ptr<Message_M2M>, int> MsgHub::map_Msg_ObsCount private
Definition at line 49 of file MsgHub.h.
Referenced by appendMsg(), and getMsg().
unordered_map<int, unordered_set<Observer*> > MsgHub::map_MsgType_ObsList private
Definition at line 47 of file MsgHub.h.
Referenced by appendMsg(), attachObserverToMsg(), detachObserverFromMsg(), and notifyObservers().
unordered_map<Observer*, queue<shared_ptr<Message_M2M> >* > MsgHub::map_Obs_MsgList private
Definition at line 48 of file MsgHub.h.
Referenced by appendMsg(), attachObserverToMsg(), getMsg(), and getMsgCount().
unordered_map<Observer*, mutex* > MsgHub::map_Obs_Mutex private
Definition at line 52 of file MsgHub.h.
Referenced by appendMsg(), attachObserverToMsg(), getMsg(), and getMsgCount().
mutex MsgHub::mutex_Msg_ObsCount private
Definition at line 55 of file MsgHub.h.
Referenced by appendMsg(), and getMsg().
mutex MsgHub::mutex_MsgType_ObsList private
Definition at line 53 of file MsgHub.h.
Referenced by appendMsg(), attachObserverToMsg(), detachObserverFromMsg(), and notifyObservers().
mutex MsgHub::mutex_Obs_MsgList private
Definition at line 54 of file MsgHub.h.
Referenced by appendMsg(), attachObserverToMsg(), getMsg(), and getMsgCount().
mutex MsgHub::mutex_Obs_Mutex private
Definition at line 56 of file MsgHub.h.
Referenced by appendMsg(), attachObserverToMsg(), getMsg(), and getMsgCount().
The documentation for this class was generated from the following files:
src/msg-handling/MsgHub.h
src/msg-handling/MsgHub.cpp