AmberOnBoard: Config Class Reference
Config Class Reference
Configuration file parser.
#include <Config.h>
Public Member Functions
Config (string path)
Constructor.
virtual ~Config ()
Destructor.
uint8_t load ()
Loads configuration from file.
vector< string > getErrors ()
Returns errors from loading.
bool getDeviceID (uint8_t &devID)
Getter for device id.
uint8_t getTermCount ()
bool getTermAt (uint8_t index, terminal &term)
bool getRealTime (server &serv)
Getter for realtime server.
bool getDeferred (server &serv)
Getter for deferred server.
bool getInnerCap (capture &cap)
Getter for in car camera.
bool getOuterCap (capture &cap)
Getter for outer car camera.
bool getPrimeCap (uint8_t &index)
Getter for primary camera index.
bool getJpegCompression (uint8_t &comp)
Getter for JPEG compression.
bool getAccType (uint8_t &type)
Getter for accelerometer type.
bool getAcc (i2cDev &dev)
Getter for accelerometer options.
bool getGPSType (uint8_t &type)
Getter for gps type.
bool getGPS (uartDev &dev)
Getter for gps options.
bool getOBD (uartDev &dev)
Getter for obd options.
Static Public Member Functions
static void tokenize (string source, vector< string > &target, char delim)
Helper method for tokenizing.
static bool shrink (string &target, string compare, size_t start, bool substr=false)
Helper method for shrinking strings.
static bool toInteger (string source, int64_t max, int64_t min, int64_t &target)
Helper method for parsing strings to integers.
Private Member Functions
void process (string source)
Processes string.
bool validate ()
Validates the configuration.
Static Private Member Functions
static vector< string > getLines (string source)
Seperates a given string by line feed.
static bool toKeyValue (string source, vector< string > &target)
Parses a string into key-value tuples.
static void toAbsPath (string source, string &target)
Converts string to absolute path.
static string toString (string option, uint8_t status)
Converts an error code to human readable output.
static uint8_t procID (vector< string > source, uint8_t &devId)
Processes device id.
static uint8_t procTerm (vector< string > source, terminal &term)
Processes terminal options.
static uint8_t procSvr (vector< string > source, server &server)
Processes server options.
static uint8_t procIface (vector< string > source, server &server)
Processes network interface options.
static uint8_t procCapture (vector< string > source, capture &capture)
Processes capture options.
static uint8_t procPrimary (vector< string > source, uint8_t &prime)
Processes primary capture option.
static uint8_t procCompression (vector< string > source, uint8_t &comp)
Processes compression option.
static uint8_t procAcc (vector< string > source, i2cDev &acc)
Processes accelerometer options.
static uint8_t procAccType (vector< string > source, uint8_t &accType)
Processes accelerometer type option.
static uint8_t procGPS (vector< string > source, uartDev &gps)
Processes gps option.
static uint8_t procGPSType (vector< string > source, uint8_t &gpsType)
Processes gps type option.
static uint8_t procOBD (vector< string > source, uartDev &obd)
Processes obd option.
Private Attributes
IOfile file
vector< string > errors
unordered_set< string > parsed
uint8_t devID
server realtime
server deferred
capture outer
capture inner
uint8_t capPrimary
uint8_t comp
uint8_t accType
i2cDev acc
uint8_t gpsType
uartDev gps
uartDev obd
Detailed Description
Configuration file parser.
This class parses a given configuration file and stores the given options for later usage.
Author
Daniel Wagenknecht
Version
2014-12-25
Definition at line 97 of file Config.h.
Constructor & Destructor Documentation
Config::Config (string path)
Constructor.
Constructor of Config instances, using 'path' as file path.
Parameters
path Path to configuration file
Definition at line 17 of file Config.cpp.
References acc, accType, i2cDev::addr, uartDev::baud, capPrimary, comp, deferred, devID, capture::fps, gps, gpsType, server::iface, capture::index, inner, outer, i2cDev::path, uartDev::path, server::port, realtime, T_ADAFRUIT, T_MPU6050, and server::target.
Config::~Config () virtual
Destructor.
Destructor of Config instances.
Definition at line 59 of file Config.cpp.
Member Function Documentation
bool Config::getAcc (i2cDev & dev)
Getter for accelerometer options.
Writes option to parameter. Returns success state.
Parameters
dev The parameter to write the option to.
Returns
True on success, false in case of error.
Definition at line 264 of file Config.cpp.
References acc, OPT_ACC_DEV, and parsed.
bool Config::getAccType (uint8_t & type)
Getter for accelerometer type.
Writes option to parameter. Returns success state.
Parameters
type The parameter to write the option to.
Returns
True on success, false in case of error.
Definition at line 246 of file Config.cpp.
References accType, OPT_ACC_TYPE, and parsed.
bool Config::getDeferred (server & serv)
Getter for deferred server.
Writes option to parameter. Returns success state.
Parameters
serv The parameter to write the option to.
Returns
True on success, false in case of error.
Definition at line 155 of file Config.cpp.
References OPT_DEF_ADDR, OPT_DEF_IFACE, parsed, and realtime.
bool Config::getDeviceID (uint8_t & devID)
Getter for device id.
Writes option to parameter. Returns success state.
Parameters
devID The parameter to write the option to.
Returns
True on success, false in case of error.
Definition at line 118 of file Config.cpp.
References devID, OPT_OBU_ID, and parsed.
vector< string > Config::getErrors ()
Returns errors from loading.
Returns all errors happened while loading the configuration.
Returns
Map<string,string> containing errors.
Definition at line 106 of file Config.cpp.
References errors.
bool Config::getGPS (uartDev & dev)
Getter for gps options.
Writes option to parameter. Returns success state.
Parameters
dev The parameter to write the option to.
Returns
True on success, false in case of error.
Definition at line 302 of file Config.cpp.
References gps, OPT_GPS_DEV, and parsed.
bool Config::getGPSType (uint8_t & type)
Getter for gps type.
Writes option to parameter. Returns success state.
Parameters
type The parameter to write the option to.
Returns
True on success, false in case of error.
Definition at line 283 of file Config.cpp.
References gpsType, OPT_GPS_TYPE, and parsed.
bool Config::getInnerCap (capture & cap)
Getter for in car camera.
Writes option to parameter. Returns success state.
Parameters
cap The parameter to write the option to.
Returns
True on success, false in case of error.
Definition at line 174 of file Config.cpp.
References inner, OPT_CAP_IN, and parsed.
bool Config::getJpegCompression (uint8_t & comp)
Getter for JPEG compression.
Writes option to parameter. Returns success state.
Parameters
comp The parameter to write the option to.
Returns
True on success, false in case of error.
Definition at line 228 of file Config.cpp.
References comp, OPT_CAP_COMP, and parsed.
vector< string > Config::getLines (string source) static private
Seperates a given string by line feed.
Tokenizes a string by '
' character and deletes comments.
Parameters
source The source string to tokenize.
Returns
A vector of tokenized strings.
Definition at line 430 of file Config.cpp.
References COMMENT, and tokenize().
Referenced by load().
bool Config::getOBD (uartDev & dev)
Getter for obd options.
Writes option to parameter. Returns success state.
Parameters
dev The parameter to write the option to.
Returns
True on success, false in case of error.
Definition at line 321 of file Config.cpp.
References obd, OPT_OBD_DEV, and parsed.
bool Config::getOuterCap (capture & cap)
Getter for outer car camera.
Writes option to parameter. Returns success state.
Parameters
cap The parameter to write the option to.
Returns
True on success, false in case of error.
Definition at line 192 of file Config.cpp.
References OPT_CAP_OUT, outer, and parsed.
bool Config::getPrimeCap (uint8_t & index)
Getter for primary camera index.
Writes option to parameter. Returns success state.
Parameters
index The parameter to write the option to.
Returns
True on success, false in case of error.
Definition at line 210 of file Config.cpp.
References capPrimary, OPT_CAP_PRIME, and parsed.
bool Config::getRealTime (server & serv)
Getter for realtime server.
Writes option to parameter. Returns success state.
Parameters
serv The parameter to write the option to.
Returns
True on success, false in case of error.
Definition at line 136 of file Config.cpp.
References OPT_REAL_ADDR, OPT_REAL_IFACE, parsed, and realtime.
bool Config::getTermAt (uint8_t index, terminal & term)
uint8_t Config::getTermCount ()
uint8_t Config::load ()
Loads configuration from file.
Loads the options from the given configuration file. Returns status indicator. In case of errors, getErrors returns a map<string,string> with the errors.
Returns
o in case of success, an error code otherwise.
Definition at line 69 of file Config.cpp.
References CONF_ERR_INVALID, CONF_ERR_NO_SUCH_FILE, CONF_ERR_READ, CONF_OK, errors, IOfile::exists(), file, getLines(), IOfile::getPath(), process(), IOparent::readOpen(), toString(), and validate().
uint8_t Config::procAcc (vector< string > source, i2cDev & acc) static private
Processes accelerometer options.
Parses the accelerometer options from 'source 'and writes it to acc. Returns status indicator.
Parameters
source Vector containing the option key-value tuple.
acc target to write to.
Returns
0 in case of success, an error code otherwise.
Definition at line 916 of file Config.cpp.
References i2cDev::addr, CONF_ERR_COUNT_MISMATCH, CONF_ERR_INVALID, CONF_OK, i2cDev::path, toAbsPath(), and toInteger().
Referenced by process().
uint8_t Config::procAccType (vector< string > source, uint8_t & accType) static private
Processes accelerometer type option.
Parses the accelerometer option from 'source 'and writes it to accType. Returns status indicator.
Parameters
source Vector containing the option key-value tuple.
accType target to write to.
Returns
0 in case of success, an error code otherwise.
Definition at line 943 of file Config.cpp.
References ACC_MPU6050, CONF_ERR_COUNT_MISMATCH, CONF_ERR_INVALID, CONF_OK, EQUALS, and T_MPU6050.
Referenced by process().
uint8_t Config::procCapture (vector< string > source, capture & cap) static private
Processes capture options.
Parses the capture information from 'source 'and writes it to cap. Returns status indicator.
Parameters
source Vector containing the option key-value tuple.
cap target to write to.
Returns
0 in case of success, an error code otherwise.
Definition at line 828 of file Config.cpp.
References CONF_ERR_COUNT_MISMATCH, CONF_ERR_INVALID, CONF_OK, capture::fps, capture::index, and toInteger().
Referenced by process().
uint8_t Config::procCompression (vector< string > source, uint8_t & comp) static private
Processes compression option.
Parses the compression option from 'source 'and writes it to comp. Returns status indicator.
Parameters
source Vector containing the option key-value tuple.
comp target to write to.
Returns
0 in case of success, an error code otherwise.
Definition at line 890 of file Config.cpp.
References CONF_ERR_COUNT_MISMATCH, CONF_ERR_INVALID, CONF_OK, and toInteger().
Referenced by process().
void Config::process (string source) private
Processes string.
Processes string 'source' from configuration
Parameters
source The string to process.
Definition at line 574 of file Config.cpp.
References acc, accType, capPrimary, comp, CONF_ERR_ALREADY_SET, CONF_ERR_TUPLE, CONF_ERR_UNKNOWN_OPT, deferred, devID, EQUALS, errors, gps, gpsType, inner, obd, OPT_ACC_DEV, OPT_ACC_TYPE, OPT_CAP_COMP, OPT_CAP_IN, OPT_CAP_OUT, OPT_CAP_PRIME, OPT_DEF_ADDR, OPT_DEF_IFACE, OPT_GPS_DEV, OPT_GPS_TYPE, OPT_OBD_DEV, OPT_OBU_ID, OPT_REAL_ADDR, OPT_REAL_IFACE, outer, parsed, procAcc(), procAccType(), procCapture(), procCompression(), procGPS(), procGPSType(), procID(), procIface(), procOBD(), procPrimary(), procSvr(), realtime, toKeyValue(), and toString().
Referenced by load().
uint8_t Config::procGPS (vector< string > source, uartDev & gps) static private
Processes gps option.
Parses the gps option from 'source 'and writes it to prime. Returns status indicator.
Parameters
source Vector containing the option key-value tuple.
gps target to write to.
Returns
0 in case of success, an error code otherwise.
Definition at line 970 of file Config.cpp.
References uartDev::baud, CONF_ERR_COUNT_MISMATCH, CONF_ERR_INVALID, CONF_OK, uartDev::path, toAbsPath(), and toInteger().
Referenced by process().
uint8_t Config::procGPSType (vector< string > source, uint8_t & gpsType) static private
Processes gps type option.
Parses the prime capture option from 'source 'and writes it to gpsType. Returns status indicator.
Parameters
source Vector containing the option key-value tuple.
gpsType target to write to.
Returns
0 in case of success, an error code otherwise.
Definition at line 997 of file Config.cpp.
References CONF_ERR_COUNT_MISMATCH, CONF_ERR_INVALID, CONF_OK, EQUALS, GPS_ADAFRUIT, and T_ADAFRUIT.
Referenced by process().
uint8_t Config::procID (vector< string > source, uint8_t & devId) static private
Processes device id.
Parses the device id option from 'source 'and writes it to devId.
Parameters
source Vector containing the option key-value tuple.
devId target to write to.
Definition at line 707 of file Config.cpp.
References CONF_ERR_COUNT_MISMATCH, CONF_ERR_INVALID, CONF_OK, and toInteger().
Referenced by process().
uint8_t Config::procIface (vector< string > source, server & server) static private
Processes network interface options.
Parses the interface information from 'source 'and writes it to server. Returns status indicator.
Parameters
source Vector containing the option key-value tuple.
server target to write to.
Returns
0 in case of success, an error code otherwise.
Definition at line 802 of file Config.cpp.
References CONF_ERR_COUNT_MISMATCH, CONF_ERR_INVALID, CONF_OK, and server::iface.
Referenced by process().
uint8_t Config::procOBD (vector< string > source, uartDev & obd) static private
Processes obd option.
Parses the obd option from 'source 'and writes it to obd. Returns status indicator.
Parameters
source Vector containing the option key-value tuple.
obd target to write to.
Returns
0 in case of success, an error code otherwise.
Definition at line 1024 of file Config.cpp.
References uartDev::baud, CONF_ERR_COUNT_MISMATCH, CONF_ERR_INVALID, CONF_OK, uartDev::path, toAbsPath(), and toInteger().
Referenced by process().
uint8_t Config::procPrimary (vector< string > source, uint8_t & prime) static private
Processes primary capture option.
Parses the prime capture option from 'source 'and writes it to prime. Returns status indicator.
Parameters
source Vector containing the option key-value tuple.
prime target to write to.
Returns
0 in case of success, an error code otherwise.
Definition at line 864 of file Config.cpp.
References CONF_ERR_COUNT_MISMATCH, CONF_ERR_INVALID, CONF_OK, and toInteger().
Referenced by process().
uint8_t Config::procSvr (vector< string > source, server & server) static private
Processes server options.
Parses the server information from 'source 'and writes it to server. Returns status indicator.
Parameters
source Vector containing the option key-value tuple.
server target to write to.
Returns
0 in case of success, an error code otherwise.
Definition at line 760 of file Config.cpp.
References CONF_ERR_COUNT_MISMATCH, CONF_ERR_INVALID, CONF_OK, server::port, server::target, and toInteger().
Referenced by process().
uint8_t Config::procTerm (vector< string > source, terminal & term) static private
Processes terminal options.
Parses the terminal information from 'source 'and writes it to term. Returns status indicator.
Parameters
source Vector containing the option key-value tuple.
devId target to write to.
Returns
0 in case of success, an error code otherwise.
Definition at line 733 of file Config.cpp.
References terminal::baud, CONF_ERR_COUNT_MISMATCH, CONF_ERR_INVALID, CONF_OK, terminal::path, toAbsPath(), and toInteger().
bool Config::shrink (string & target, string compare, size_t start, bool substr = false) static
Helper method for shrinking strings.
Determines in string 'target' beginning at position 'start' the first and the last character not contained in 'compare'. If 'substr' is true, a substring is builded from these bounds. Otherwise, the characters in these bounds are erased.
Parameters
target The source string and the target where the result is written to.
compare String containing all characters to check.
start the start position in the string.
substr Whether to build a substring or delete the found characters.
Returns
true on success, false in case of error.
Definition at line 361 of file Config.cpp.
Referenced by toKeyValue().
void Config::toAbsPath (string source, string & target) static private
Converts string to absolute path.
Checks whether string contains an absolute path. Appends "/dev/" as default if not.
Parameters
source The source string to convert.
target The target string to write the result to.
Definition at line 503 of file Config.cpp.
References DEV_PATH.
Referenced by procAcc(), procGPS(), procOBD(), and procTerm().
bool Config::toInteger (string source, int64_t max, int64_t min, int64_t & target) static
Helper method for parsing strings to integers.
Parses source to an integer and checks if the result is in bounds between 'min' and 'max'. The result is written to 'target'.
Parameters
source The source string to parse.
max Upper integer bounds.
min Lower integer bounds.
target Targeet integer where the result is written to.
Returns
true on success, false in case of error.
Definition at line 404 of file Config.cpp.
Referenced by procAcc(), procCapture(), procCompression(), procGPS(), procID(), procOBD(), procPrimary(), procSvr(), and procTerm().
void Config::tokenize (string source, vector< string > & target, char delim) static
Helper method for tokenizing.
Tokenizes string 'source' by delimiter 'delim' and writes all tokens to 'target'
Parameters
source Source string.
target Target vector.
delim Delimiter for tokenizing.
Definition at line 341 of file Config.cpp.
Referenced by getLines(), and toKeyValue().
bool Config::toKeyValue (string source, vector< string > & target) static private
Parses a string into key-value tuples.
Tokenizes a string by key-value delimiter and splits the value into subvalues.
Parameters
source The source string to parse.
target The target vector, containing the key at first position.
Returns
true on success, false in case of error.
Definition at line 468 of file Config.cpp.
References KEY_VAL_DELIM, shrink(), tokenize(), and VAL_VAL_DELIM.
Referenced by process().
string Config::toString (string option, uint8_t status) static private
Converts an error code to human readable output.
Returns error code 'status' for option 'option' in human readable form
Parameters
option The option causing the error.
status The error code.
Returns
Error string in human readable form.
Definition at line 520 of file Config.cpp.
References CONF_ERR_ALREADY_SET, CONF_ERR_COUNT_MISMATCH, CONF_ERR_INVALID, CONF_ERR_NO_SUCH_FILE, CONF_ERR_READ, CONF_ERR_TUPLE, CONF_ERR_UNKNOWN_OPT, and CONF_ERR_UNSET.
Referenced by load(), process(), and validate().
bool Config::validate () private
Validates the configuration.
Validates the given options.
Returns
true if configuration is valid, false otherwise.
Definition at line 663 of file Config.cpp.
References capPrimary, CONF_ERR_INVALID, CONF_ERR_UNSET, errors, capture::index, inner, OPT_ACC_DEV, OPT_ACC_TYPE, OPT_CAP_COMP, OPT_CAP_IN, OPT_CAP_OUT, OPT_CAP_PRIME, OPT_DEF_ADDR, OPT_DEF_IFACE, OPT_GPS_DEV, OPT_GPS_TYPE, OPT_OBU_ID, OPT_REAL_ADDR, OPT_REAL_IFACE, parsed, and toString().
Referenced by load().
Member Data Documentation
i2cDev Config::acc private
Definition at line 152 of file Config.h.
Referenced by Config(), getAcc(), and process().
uint8_t Config::accType private
Definition at line 151 of file Config.h.
Referenced by Config(), getAccType(), and process().
uint8_t Config::capPrimary private
Definition at line 145 of file Config.h.
Referenced by Config(), getPrimeCap(), process(), and validate().
uint8_t Config::comp private
Definition at line 148 of file Config.h.
Referenced by Config(), getJpegCompression(), and process().
server Config::deferred private
Definition at line 141 of file Config.h.
Referenced by Config(), and process().
uint8_t Config::devID private
Definition at line 138 of file Config.h.
Referenced by Config(), getDeviceID(), and process().
vector<string> Config::errors private
Definition at line 132 of file Config.h.
Referenced by getErrors(), load(), process(), and validate().
IOfile Config::file private
Definition at line 129 of file Config.h.
Referenced by load().
uartDev Config::gps private
Definition at line 156 of file Config.h.
Referenced by Config(), getGPS(), and process().
uint8_t Config::gpsType private
Definition at line 155 of file Config.h.
Referenced by Config(), getGPSType(), and process().
capture Config::inner private
Definition at line 144 of file Config.h.
Referenced by Config(), getInnerCap(), process(), and validate().
uartDev Config::obd private
Definition at line 159 of file Config.h.
Referenced by getOBD(), and process().
capture Config::outer private
Definition at line 144 of file Config.h.
Referenced by Config(), getOuterCap(), and process().
unordered_set<string> Config::parsed private
Definition at line 135 of file Config.h.
Referenced by getAcc(), getAccType(), getDeferred(), getDeviceID(), getGPS(), getGPSType(), getInnerCap(), getJpegCompression(), getOBD(), getOuterCap(), getPrimeCap(), getRealTime(), process(), and validate().
server Config::realtime private
Definition at line 141 of file Config.h.
Referenced by Config(), getDeferred(), getRealTime(), and process().
The documentation for this class was generated from the following files:
src/io-handling/Config.h
src/io-handling/Config.cpp