AmberOnBoard: OpCurveDetection Class Reference
OpCurveDetection Class Reference
Class for detecting curves in video stream.
#include <OpCurveDetection.h>
Classes
struct Polynomial
Public Member Functions
virtual uint8_t process (unordered_map< string, shared_ptr< Value >> &results)
The main function to start.
uint8_t initialize ()
Initialisation of LookUp tables.
OpCurveDetection ()
~OpCurveDetection ()
Public Member Functions inherited from ImgOperator
ImgOperator (uint8_t type, uint8_t captureCount)
Constructor.
uint8_t getType ()
Getter for operator type.
virtual ~ImgOperator ()=0
Destructor.
uint8_t apply (unordered_map< string, shared_ptr< Value >> &results)
Applies operator.
virtual uint8_t getCaptureCount ()
Getter for capture count.
virtual void createCaptures (uint8_t captureCount)
Create captures.
Public Member Functions inherited from ValContainer
ValContainer ()
Constructor.
virtual ~ValContainer ()=0
Destructor.
virtual void createValue (string name, shared_ptr< Value > val)
Creates new value for this container.
void deleteKey (string name)
Deletes a value from container.
virtual uint8_t setValue (string name, const shared_ptr< Value > &val)
Sets a value in the container.
virtual uint8_t getValue (string name, shared_ptr< Value > &val)
Gets a value from container.
virtual bool initialized ()
Checks if all values are initialized.
uint8_t getValueCount ()
Gets value count.
Private Types
enum Side { LEFT, RIGHT, BOTH, NEITHER }
Private Member Functions
void reduceRowsCount (Mat &img)
Removes unnecessary rows.
void searchForMarking (Mat &img)
Finds edges (street marking) in image.
void conv2BirdView (Mat &img)
void searchForMarkingPoints (Mat &img, map< double, double > &leftLine, map< double, double > &rightLine)
Finds sets of points of left and right street marking.
Side updateMarkingPoints (Mat &img, map< double, double > &leftLine, map< double, double > &rightLine)
Searches marking points using information of calculated polynomials from previous frame.
void findMarkingPoints (Mat &img, map< double, double > &leftLine, map< double, double > &rightLine, Side side)
Searches marking points using no informations from previous frame.
Polynomial calcFunction (map< double, double > &linePoints)
Calculates a polynomial for map of points.
double getRadius (Polynomial &l, Polynomial &r)
Returns radius of a curve Compares radius results for left and right lines and decides which one is more reliable.
double calcRadius (Polynomial &line)
Calculate radius of one polynomial.
void drawPolynomials (Mat &img, Polynomial &l, Polynomial &r)
debugging Draws polynomials of the left and right marking lines with brightness 128 on the Image for Debugging purposes
void drawLines (Mat &img)
Draws Lines from lookup table on the Full Image for debugging.
Private Attributes
int max_distance = 10
int threshold = 10
int marking_width = 80
int width_multiplier = 5
int pix_to_meter_k = 160
int marking_search_area_pix = 80
int calc_radius_at_meter = 10
int cam_view_angle = 47
double cam_height = 1.9
double cam_offset = 3.0
bool initialized
map< double, int > lookupForFullImg
double * lookup
int nlookup
Polynomial oldLeftMarking
Polynomial oldRightMarking
Additional Inherited Members
Protected Attributes inherited from ImgOperator
uint8_t type
vector< string > captureIDs
Protected Attributes inherited from ValContainer
unordered_map< string,
shared_ptr< Value > > config
Detailed Description
Class for detecting curves in video stream.
Image operator for detecting curves in a video stream.
Author
Askar Massalimov
Version
2014-01-06
Definition at line 41 of file OpCurveDetection.h.
Member Enumeration Documentation
enum OpCurveDetection::Side private
Enumerator
LEFT
RIGHT
BOTH
NEITHER
Definition at line 85 of file OpCurveDetection.h.
Constructor & Destructor Documentation
OpCurveDetection::OpCurveDetection ()
Definition at line 11 of file OpCurveDetection.cpp.
References ARG_CAM_CALC_RADIUS_AT_METER, ARG_CAM_HEIGHT, ARG_CAM_MARK_WIDTH, ARG_CAM_MARKING_SEARCH_AREA_PIX, ARG_CAM_MAX_DIST, ARG_CAM_OFFSET, ARG_CAM_PIX_TO_METER_K, ARG_CAM_THRESHOLD, ARG_CAM_VIEW_ANGLE_V, ARG_CAM_WIDTH_MULTIPLIER, ARG_OP_ACTIVE, ValContainer::createValue(), ValContainer::initialized(), lookup, and nlookup.
OpCurveDetection::~OpCurveDetection ()
Definition at line 31 of file OpCurveDetection.cpp.
References lookup.
Member Function Documentation
OpCurveDetection::Polynomial OpCurveDetection::calcFunction (map< double, double > & points) private
Calculates a polynomial for map of points.
Calculates a polynomial of 2 grad for a set of points using approximation algorithm to represent a marking line as a function
Parameters
Set of points of the left or right marking line map<double, double> points (double stands for map<distance from car in meter, horizontal coordinates in meter> points)
Returns
Calculated polynomial for the current set of marking points
Definition at line 486 of file OpCurveDetection.cpp.
References OpCurveDetection::Polynomial::a, OpCurveDetection::Polynomial::b, OpCurveDetection::Polynomial::c, OpCurveDetection::Polynomial::ERROR_FLAG, and OpCurveDetection::Polynomial::pointsUsed.
Referenced by process().
double OpCurveDetection::calcRadius (Polynomial & line) private
Calculate radius of one polynomial.
calculating curve radius at the certain point x of the F(x) = a*x*x + b*x + c radius = ((1 + f'(x)^2)^(3/2))/|f"(x)|
Parameters
line Polynomial of the left or right marking line
Returns
Radius in meter(positive if the marking turns right and negative if left)
Definition at line 585 of file OpCurveDetection.cpp.
References OpCurveDetection::Polynomial::a, OpCurveDetection::Polynomial::b, and calc_radius_at_meter.
Referenced by getRadius().
void OpCurveDetection::conv2BirdView (Mat & img) private
Changes the view from the drivers perspective to the birdview by warping the image
Parameters
img Binary camera image (containing only necessary rows with found marking as 255)
getting corresponding rows of both Mats: (row to read from) -> analysing -> (row to write to)
Definition at line 235 of file OpCurveDetection.cpp.
References cam_offset, lookup, and width_multiplier.
Referenced by process().
void OpCurveDetection::drawLines (Mat & img) private
Draws Lines from lookup table on the Full Image for debugging.
Parameters
img full image
Definition at line 694 of file OpCurveDetection.cpp.
References lookupForFullImg.
void OpCurveDetection::drawPolynomials (Mat & img, Polynomial & l, Polynomial & r) private
debugging Draws polynomials of the left and right marking lines with brightness 128 on the Image for Debugging purposes
Parameters
img Gray scale camera image
l Left marking line polynomial
r Right marking line polynomial
Definition at line 206 of file OpCurveDetection.cpp.
References OpCurveDetection::Polynomial::a, OpCurveDetection::Polynomial::b, OpCurveDetection::Polynomial::c, lookup, and pix_to_meter_k.
void OpCurveDetection::findMarkingPoints (Mat & img, map< double, double > & leftLine, map< double, double > & rightLine, Side dontDoFor) private
Searches marking points using no informations from previous frame.
Is being used on the start of the program or if some results of updateMarkingPoints(..) are not valid
There is an area defined, with center in laneCenter and wide as 2 * maxDistFromLaneCenter In this area is being searched for leftLine and rightLine points. If both found in one Image row -> laneCenter will be updated
Parameters
img Binary camera image (containing only necessary rows, BirdView scaled)
leftLine set of points of the left street marking
rightLine set of points of the right street marking
dontDoFor Enum Side - for which side of the street marking this function should not be applied to
Definition at line 390 of file OpCurveDetection.cpp.
References LEFT, lookup, NEITHER, pix_to_meter_k, RIGHT, and width_multiplier.
Referenced by searchForMarkingPoints().
double OpCurveDetection::getRadius (Polynomial & l, Polynomial & r) private
Returns radius of a curve Compares radius results for left and right lines and decides which one is more reliable.
Parameters
l Polynomial of the left marking line
r Polynomial of the right marking line
Returns
Radius (negative if left turn, positive if right turn)
Definition at line 551 of file OpCurveDetection.cpp.
References calcRadius(), nlookup, and OpCurveDetection::Polynomial::pointsUsed.
Referenced by process().
uint8_t OpCurveDetection::initialize ()
Initialisation of LookUp tables.
This function creates a LookUp table which assigns a distance in meter from the front of a car to the corresponding line number on the image.
the formula is: linenumber = (numberOfLines/2)(1 + cameraHeight/((distance + camOffset)*tan(vAngleOfView/2)))
Formula is calculated assuming the street is even and the horizon line lies exacly in the midle of the image
vAngleOfView - vertical angle of view of the camera camHeight - distance from camera to the street camOffset - distance from camera to the fromt of the car distance - distance from the front of the car to some point in meters
Parameters
img Source image
Definition at line 616 of file OpCurveDetection.cpp.
References ARG_CAM_CALC_RADIUS_AT_METER, ARG_CAM_HEIGHT, ARG_CAM_MARK_WIDTH, ARG_CAM_MARKING_SEARCH_AREA_PIX, ARG_CAM_MAX_DIST, ARG_CAM_OFFSET, ARG_CAM_PIX_TO_METER_K, ARG_CAM_THRESHOLD, ARG_CAM_VIEW_ANGLE_V, ARG_CAM_WIDTH_MULTIPLIER, calc_radius_at_meter, cam_height, cam_offset, cam_view_angle, ValContainer::getValue(), IMG_HEIGHT, ValContainer::initialized(), lookup, lookupForFullImg, marking_search_area_pix, marking_width, max_distance, nlookup, OK, PI, pix_to_meter_k, threshold, and width_multiplier.
Referenced by process().
uint8_t OpCurveDetection::process (unordered_map< string, shared_ptr< Value >> & results) virtual
The main function to start.
Parameters
radius Double to write radius to
Implements ImgOperator.
Definition at line 40 of file OpCurveDetection.cpp.
References ARG_OP_ACTIVE, calcFunction(), ImgOperator::captureIDs, conv2BirdView(), ERR_UNKNOWN, OpCurveDetection::Polynomial::ERROR_FLAG, getRadius(), ValContainer::getValue(), initialize(), ValContainer::initialized(), OK, oldLeftMarking, oldRightMarking, reduceRowsCount(), RES_CURVE_RADIUS, searchForMarking(), and searchForMarkingPoints().
void OpCurveDetection::reduceRowsCount (Mat & img) private
Removes unnecessary rows.
Deletes all unnecessary rows of the image, that are not listed in the lookup table. It is being made to reduce the size of the Image only to particular rows, containing important information. All of the remaining rows are ordered in the same order as mentioned in lookup (row 0 - 25m, 1 - 24m, 2 - 23m ...).
Parameters
img Gray scale camera image
Definition at line 105 of file OpCurveDetection.cpp.
References lookupForFullImg.
Referenced by process().
void OpCurveDetection::searchForMarking (Mat & img) private
Finds edges (street marking) in image.
This function implements street marking lines detection and writes analysed binary(0 or 255) image back into img
Parameters
img Gray scale camera image (containing only necessary rows)
Definition at line 138 of file OpCurveDetection.cpp.
References lookup, lookupForFullImg, marking_width, max_distance, and threshold.
Referenced by process().
void OpCurveDetection::searchForMarkingPoints (Mat & img, map< double, double > & leftLine, map< double, double > & rightLine) private
Finds sets of points of left and right street marking.
Writes points of the left marking line and points of the right marking line into two maps This method decide whether to use updateMarkingPoints or findMarkingPoints function
Parameters
img Binary camera image (containing only necessary rows, BirdView scaled)
leftLine set of points of the left street marking
rightLine set of points of the right street marking
Definition at line 272 of file OpCurveDetection.cpp.
References BOTH, findMarkingPoints(), and updateMarkingPoints().
Referenced by process().
OpCurveDetection::Side OpCurveDetection::updateMarkingPoints (Mat & img, map< double, double > & leftLine, map< double, double > & rightLine) private
Searches marking points using information of calculated polynomials from previous frame.
Parameters
img Binary camera image (containing only necessary rows, BirdView scaled)
leftLine set of points of the left street marking
rightLine set of points of the right street marking
Returns
Enum Side - for which side(s) of the street marking are results good enough
Definition at line 289 of file OpCurveDetection.cpp.
References OpCurveDetection::Polynomial::a, OpCurveDetection::Polynomial::b, BOTH, OpCurveDetection::Polynomial::c, LEFT, lookup, marking_search_area_pix, NEITHER, oldLeftMarking, oldRightMarking, pix_to_meter_k, and RIGHT.
Referenced by searchForMarkingPoints().
Member Data Documentation
int OpCurveDetection::calc_radius_at_meter = 10 private
Definition at line 56 of file OpCurveDetection.h.
Referenced by calcRadius(), and initialize().
double OpCurveDetection::cam_height = 1.9 private
Definition at line 60 of file OpCurveDetection.h.
Referenced by initialize().
double OpCurveDetection::cam_offset = 3.0 private
Definition at line 61 of file OpCurveDetection.h.
Referenced by conv2BirdView(), and initialize().
int OpCurveDetection::cam_view_angle = 47 private
Definition at line 59 of file OpCurveDetection.h.
Referenced by initialize().
bool OpCurveDetection::initialized private
Definition at line 64 of file OpCurveDetection.h.
double* OpCurveDetection::lookup private
Definition at line 68 of file OpCurveDetection.h.
Referenced by conv2BirdView(), drawPolynomials(), findMarkingPoints(), initialize(), OpCurveDetection(), searchForMarking(), updateMarkingPoints(), and ~OpCurveDetection().
map<double, int> OpCurveDetection::lookupForFullImg private
Definition at line 67 of file OpCurveDetection.h.
Referenced by drawLines(), initialize(), reduceRowsCount(), and searchForMarking().
int OpCurveDetection::marking_search_area_pix = 80 private
Definition at line 55 of file OpCurveDetection.h.
Referenced by initialize(), and updateMarkingPoints().
int OpCurveDetection::marking_width = 80 private
Definition at line 52 of file OpCurveDetection.h.
Referenced by initialize(), and searchForMarking().
int OpCurveDetection::max_distance = 10 private
Definition at line 50 of file OpCurveDetection.h.
Referenced by initialize(), and searchForMarking().
int OpCurveDetection::nlookup private
Definition at line 69 of file OpCurveDetection.h.
Referenced by getRadius(), initialize(), and OpCurveDetection().
Polynomial OpCurveDetection::oldLeftMarking private
Definition at line 81 of file OpCurveDetection.h.
Referenced by process(), and updateMarkingPoints().
Polynomial OpCurveDetection::oldRightMarking private
Definition at line 82 of file OpCurveDetection.h.
Referenced by process(), and updateMarkingPoints().
int OpCurveDetection::pix_to_meter_k = 160 private
Definition at line 54 of file OpCurveDetection.h.
Referenced by drawPolynomials(), findMarkingPoints(), initialize(), and updateMarkingPoints().
int OpCurveDetection::threshold = 10 private
Definition at line 51 of file OpCurveDetection.h.
Referenced by initialize(), and searchForMarking().
int OpCurveDetection::width_multiplier = 5 private
Definition at line 53 of file OpCurveDetection.h.
Referenced by conv2BirdView(), findMarkingPoints(), and initialize().
The documentation for this class was generated from the following files:
src/img-handling/OpCurveDetection.h
src/img-handling/OpCurveDetection.cpp