AmberOnBoard: IOserial Class Reference
IOserial Class Reference
Concrete class for serial ports.
#include <IOserial.h>
Public Member Functions
IOserial (string path, uint32_t baud)
Constructor.
virtual ~IOserial ()
Destructor.
virtual uint8_t open (uint8_t type, bool force=false)
Open serial port.
virtual bool isOpen ()
Checks if port is open.
virtual uint8_t setup ()
Sets up serial port.
uint8_t setBaud (uint32_t baud)
Sets baud rate of the port.
uint32_t getBaud ()
Getter for baud rate.
virtual uint8_t reset ()
Restores serial port settings.
virtual uint8_t close ()
Closes serial port.
Public Member Functions inherited from IOparent
IOparent ()
Constructor.
virtual ~IOparent ()
Destructor.
void setActive (bool active)
Sets activity status.
bool isActive ()
Check instance activity.
uint8_t readSafe (string &input, uint8_t delim)
Safely reads from input.
uint8_t readOpen (string &input, uint8_t delim)
Opens input and reads from it.
uint8_t read (string &input, uint8_t delim)
Read from input.
uint8_t writeSafe (string output)
Safely writes string to output.
uint8_t write (string output)
Writes string to output.
uint8_t appendSafe (string output)
Safely appends string to output.
uint8_t appendOpen (string output)
Opens output in append mode and writes to it.
uint8_t append (string output)
Opens output in append mode and writes to it.
Protected Member Functions
virtual uint8_t getChar ()
Read byte.
virtual uint8_t putString (string &output)
Writes string to serial port.
Private Attributes
string path
speed_t baud
FILE * file
struct termios backupConfig usedConfig
Static Private Attributes
static uint8_t cmpBlock [sizeof(termios)] = {0}
Detailed Description
Concrete class for serial ports.
Concrete class, handling a serial port in file system and offering access to it.
Author
Daniel Wagenknecht
Version
2014-12-19
Definition at line 23 of file IOserial.h.
Constructor & Destructor Documentation
IOserial::IOserial (string path, uint32_t baud)
Constructor.
Constructor of IOserial instances, using 'path' as file path and 'baud' as baud rate.
Parameters
path Path to serial port.
baud Baud rate to use.
Definition at line 20 of file IOserial.cpp.
References file, path, setBaud(), and usedConfig.
IOserial::~IOserial () virtual
Destructor.
Destructor of IOserial instances. Resets port settings and closes corresponding descriptor.
Definition at line 34 of file IOserial.cpp.
References close(), and reset().
Member Function Documentation
uint8_t IOserial::close () virtual
Closes serial port.
Closes the serial port Returns status indicator.
Returns
0 in case of success, an error code otherwise.
Implements IOparent.
Definition at line 246 of file IOserial.cpp.
References file, IO_ERR_CLOSE, IO_OK, isOpen(), reset(), and IOparent::setActive().
Referenced by open(), GpsAdafruit::~GpsAdafruit(), ~IOserial(), and OBDReader::~OBDReader().
uint32_t IOserial::getBaud ()
Getter for baud rate.
Returns the baud rate currently used for serial communication.
Returns
Current baud rate.
Definition at line 189 of file IOserial.cpp.
References baud.
Referenced by getChar().
uint8_t IOserial::getChar () protected virtual
Read byte.
Reads a single byte from serial port and returns it. If read fails, the read process gets repeated until either a new byte arrives or this instance is set to inactive.
Returns
Next character in file.
Implements IOparent.
Definition at line 282 of file IOserial.cpp.
References file, getBaud(), and IOparent::isActive().
bool IOserial::isOpen () virtual
Checks if port is open.
Returns whether the specified port is already opened by this instance or not.
Returns
true if port is open, false otherwise.
Implements IOparent.
Definition at line 97 of file IOserial.cpp.
References file.
Referenced by close(), open(), and setBaud().
uint8_t IOserial::open (uint8_t type, bool force = false) virtual
Open serial port.
Opens the serial port in mode 'type'. If 'force' is true and the port is alread open, a reopen is forced. Type must be one of: OPEN_W = for writing Open_R = OPEN_A = for appending Returns status indicator.
Parameters
type Mode of opening.
force flag (true for forcing reopen).
Returns
0 in case of success, an error code otherwise.
Implements IOparent.
Definition at line 52 of file IOserial.cpp.
References close(), file, IO_ERR_OPEN, IO_OK, isOpen(), OPEN_A, OPEN_R, OPEN_W, path, IOparent::setActive(), and setup().
Referenced by GpsAdafruit::initialize().
uint8_t IOserial::putString (string & output) protected virtual
Writes string to serial port.
Writes all bytes of 'output' to the serial port. Waits until all bytes written are actually sent to device. Returns status indicator.
Returns
0 in case of success, an error code otherwise.
Implements IOparent.
Definition at line 304 of file IOserial.cpp.
References file, IO_ERR_WRITE, and IO_OK.
uint8_t IOserial::reset () virtual
Restores serial port settings.
Resets serial port settings to origin values. Returns status indicator.
Returns
0 in case of success, an error code otherwise.
Implements IOparent.
Definition at line 225 of file IOserial.cpp.
References cmpBlock, file, IO_ERR_RESET, and IO_OK.
Referenced by close(), and ~IOserial().
uint8_t IOserial::setBaud (uint32_t baud)
Sets baud rate of the port.
Sets the baud rate used for this port to 'baud'. If the port is already open, the changes are also applied directly to the port. Returns status indicator.
Parameters
baud The baud rate of this serial port.
Returns
0 in case of success, an error code otherwise.
Definition at line 147 of file IOserial.cpp.
References IO_ERR_SETUP, IO_OK, isOpen(), and setup().
Referenced by IOserial(), and GpsAdafruit::setBaud().
uint8_t IOserial::setup () virtual
Sets up serial port.
Sets up serial port for usage. Returns status indicator.
Returns
0 in case of success, an error code otherwise.
Implements IOparent.
Definition at line 110 of file IOserial.cpp.
References baud, cmpBlock, file, IO_ERR_SETUP, IO_OK, and usedConfig.
Referenced by open(), and setBaud().
Member Data Documentation
speed_t IOserial::baud private
Definition at line 53 of file IOserial.h.
Referenced by getBaud(), and setup().
uint8_t IOserial::cmpBlock = {0} static private
Definition at line 60 of file IOserial.h.
Referenced by reset(), and setup().
FILE* IOserial::file private
Definition at line 56 of file IOserial.h.
Referenced by close(), getChar(), IOserial(), isOpen(), open(), putString(), reset(), and setup().
string IOserial::path private
Definition at line 50 of file IOserial.h.
Referenced by IOserial(), and open().
struct termios backupConfig IOserial::usedConfig private
Definition at line 59 of file IOserial.h.
Referenced by IOserial(), and setup().
The documentation for this class was generated from the following files:
src/io-handling/instances/IOserial.h
src/io-handling/instances/IOserial.cpp