AmberOnBoard: IOparent Class Reference
IOparent Class Reference abstract
Abstract parent for io handling.
#include <IOparent.h>
Public Member Functions
IOparent ()
Constructor.
virtual ~IOparent ()
Destructor.
void setActive (bool active)
Sets activity status.
bool isActive ()
Check instance activity.
virtual uint8_t open (uint8_t type, bool force=false)=0
virtual bool isOpen ()=0
virtual uint8_t setup ()=0
uint8_t readSafe (string &input, uint8_t delim)
Safely reads from input.
uint8_t readOpen (string &input, uint8_t delim)
Opens input and reads from it.
uint8_t read (string &input, uint8_t delim)
Read from input.
uint8_t writeSafe (string output)
Safely writes string to output.
uint8_t write (string output)
Writes string to output.
uint8_t appendSafe (string output)
Safely appends string to output.
uint8_t appendOpen (string output)
Opens output in append mode and writes to it.
uint8_t append (string output)
Opens output in append mode and writes to it.
virtual uint8_t reset ()=0
virtual uint8_t close ()=0
Protected Member Functions
virtual uint8_t getChar ()=0
virtual uint8_t putString (string &output)=0
Private Attributes
bool active
mutex rw_mutex
Detailed Description
Abstract parent for io handling.
Abstract base class for input / output handling.
Author
Daniel Wagenknecht
Version
2014-12-18
Definition at line 36 of file IOparent.h.
Constructor & Destructor Documentation
IOparent::IOparent ()
Constructor.
Default constructor of IOparent instances.
Definition at line 15 of file IOparent.cpp.
References active.
IOparent::~IOparent () virtual
Destructor.
Destructor of IOparent instances.
Definition at line 23 of file IOparent.cpp.
Member Function Documentation
uint8_t IOparent::append (string output)
Opens output in append mode and writes to it.
Appends string 'output' to file / port. Returns status indicator.
Parameters
output String which gets written.
Returns
0 in case of success, an error code otherwise.
Definition at line 254 of file IOparent.cpp.
References putString(), and rw_mutex.
Referenced by appendOpen(), and write().
uint8_t IOparent::appendOpen (string output)
Opens output in append mode and writes to it.
Opens the port / file before writing to it. Note: no reopen is forced when calling the actual open method. Returns status indicator.
Parameters
output String which gets written.
Returns
0 in case of success, an error code otherwise.
Definition at line 227 of file IOparent.cpp.
References append(), IO_OK, isOpen(), open(), and OPEN_A.
Referenced by appendSafe(), OBDReader::getAdapter(), OBDReader::getAirflow(), OBDReader::getAirpressureInlet(), OBDReader::getCoolantTemp(), OBDReader::getEngineControlKM(), OBDReader::getEngineLoad(), OBDReader::getFuelLevel(), OBDReader::getFuelPressure(), OBDReader::getInletAirTemp(), OBDReader::getRPM(), OBDReader::getSpeed(), GpsAdafruit::printFrame(), OBDReader::reset(), and OBDReader::setup().
uint8_t IOparent::appendSafe (string output)
Safely appends string to output.
Safely appends string to the port / file, which means the origin port / file configuration is restored after operation. Exemplary usage of this method is while dealing with the stdin/stdout of the current terminal at "/dev/tty". Not resetting the port before closing the application in this case causes strange behavior of the console, since echo and canonical input get manipulated. Returns status indicator.
Parameters
output String which gets written.
Returns
0 in case of success, an error code otherwise.
Definition at line 203 of file IOparent.cpp.
References appendOpen(), and reset().
virtual uint8_t IOparent::close () pure virtual
Implemented in IOi2cBus, IOserial, and IOfile.
virtual uint8_t IOparent::getChar () protected pure virtual
Implemented in IOi2cBus, IOserial, and IOfile.
Referenced by read().
bool IOparent::isActive ()
Check instance activity.
Returns the instances current activity status.
Returns
true if instance is active, false otherwise.
Definition at line 41 of file IOparent.cpp.
References active.
Referenced by IOserial::getChar(), OBDReader::run(), and GpsAdafruit::run().
virtual bool IOparent::isOpen () pure virtual
Implemented in IOi2cBus, IOfile, and IOserial.
Referenced by appendOpen(), read(), and readOpen().
virtual uint8_t IOparent::open (uint8_t type, bool force = false) pure virtual
Implemented in IOi2cBus, IOfile, and IOserial.
Referenced by appendOpen(), readOpen(), and write().
virtual uint8_t IOparent::putString (string & output) protected pure virtual
Implemented in IOi2cBus, IOserial, and IOfile.
Referenced by append().
uint8_t IOparent::read (string & input, uint8_t delim)
Read from input.
Reads from the port / file until either the instance is deactivated or 'delim' was read. The result gets written to 'input'. Returns status indicator.
Parameters
input Target to write result to.
delim Delimiter to stop the read process at.
Returns
0 in case of success, an error code otherwise.
Definition at line 112 of file IOparent.cpp.
References active, getChar(), IO_ERR_OPEN, IO_OK, isOpen(), and rw_mutex.
Referenced by IOi2cBus::getChar(), IOi2cBus::readBytes(), and readOpen().
uint8_t IOparent::readOpen (string & input, uint8_t delim)
Opens input and reads from it.
Opens the port / file before reading from it. Note: no reopen is forced when calling the actual open method. Returns status indicator.
Parameters
input Target to write result to.
delim Delimiter to stop the read process at.
Returns
0 in case of success, an error code otherwise.
Definition at line 84 of file IOparent.cpp.
References IO_OK, isOpen(), open(), OPEN_R, and read().
Referenced by OBDReader::getAdapter(), OBDReader::getOBDAnswer(), Config::load(), readSafe(), OBDReader::reset(), GpsAdafruit::run(), and OBDReader::setup().
uint8_t IOparent::readSafe (string & input, uint8_t delim)
Safely reads from input.
Safely reads from input, which means a readopen is called and the origin port / file configuration is restored after operation. Exemplary usage of this method is while dealing with the stdin/stdout of the current terminal at "/dev/tty". Not resetting the port before closing the application in this case causes strange behavior of the console, since echo and canonical input get manipulated. Returns status indicator.
Parameters
input Target to write result to.
delim Delimiter to stop the read process at.
Returns
0 in case of success, an error code otherwise.
Definition at line 58 of file IOparent.cpp.
References readOpen(), and reset().
virtual uint8_t IOparent::reset () pure virtual
Implemented in IOi2cBus, IOserial, and IOfile.
Referenced by appendSafe(), readSafe(), and writeSafe().
void IOparent::setActive (bool active)
Sets activity status.
Sets the instances activity status to 'active'.
Parameters
active The new activity indicator.
Definition at line 31 of file IOparent.cpp.
References active.
Referenced by IOfile::close(), IOserial::close(), IOserial::open(), IOfile::open(), and IOi2cBus::request().
virtual uint8_t IOparent::setup () pure virtual
Implemented in IOi2cBus, IOfile, and IOserial.
uint8_t IOparent::write (string output)
Writes string to output.
Forces a port / file reopen and appends 'output' to freshly opened file. Note: Opening a file in write mode deletes the content before writing to it. Returns status indicator.
Parameters
output String which gets written.
Returns
0 in case of success, an error code otherwise.
Definition at line 175 of file IOparent.cpp.
References append(), IO_OK, open(), and OPEN_W.
Referenced by IOi2cBus::putString(), IOi2cBus::readBytes(), IOi2cBus::writeBytes(), writeSafe(), and IOi2cBus::writeWords().
uint8_t IOparent::writeSafe (string output)
Safely writes string to output.
Safely writes to the port / file, which means the origin port / file configuration is restored after operation. Exemplary usage of this method is while dealing with the stdin/stdout of the current terminal at "/dev/tty". Not resetting the port before closing the application in this case causes strange behavior of the console, since echo and canonical input get manipulated. Returns status indicator.
Parameters
output String which gets written.
Returns
0 in case of success, an error code otherwise.
Definition at line 151 of file IOparent.cpp.
References reset(), and write().
Member Data Documentation
bool IOparent::active private
Definition at line 77 of file IOparent.h.
Referenced by IOparent(), isActive(), read(), and setActive().
mutex IOparent::rw_mutex private
Definition at line 80 of file IOparent.h.
Referenced by append(), and read().
The documentation for this class was generated from the following files:
src/io-handling/instances/IOparent.h
src/io-handling/instances/IOparent.cpp