AmberOnBoard: Child Class Reference
Child Class Reference abstract
Abstract parent class of module children.
#include <Child.h>
Public Member Functions
Child ()
Constructor.
virtual ~Child ()
Destructor.
virtual int run ()=0
void attachObserver (Observer *observer)
Attaches an Observer instance to Child.
void detachObserver (Observer *observer)
Detaches an Observer instance from Child.
void notifyObservers ()
Notifies observers about new messages.
void terminate ()
Sets termination flag of this child.
bool isTerminating ()
Returns the value of the termination flag.
void term_wait ()
Waits until terminate condition is true.
shared_ptr< Message_M2C > in_pop ()
Get next pending input.
void in_push (shared_ptr< Message_M2C > field)
Puts new message to input list.
uint8_t in_count ()
Get input count.
shared_ptr< Message_M2C > out_pop ()
Get next pending output.
void out_push (shared_ptr< Message_M2C > field)
Puts new message to output list.
uint8_t out_count ()
Get output count.
void out_wait ()
Wait for output messages.
void out_wait (uint32_t useconds)
Wait for output messages.
Private Attributes
unordered_set< Observer * > observers
mutex obsMutex
queue< shared_ptr< Message_M2C > > outgoing
queue< shared_ptr< Message_M2C > > incoming
mutex inMutex
mutex outMutex
mutex oWait
mutex termWait
condition_variable condition
condition_variable termCondition
bool terminating
Detailed Description
Abstract parent class of module children.
Abstract parent class of module children. Child instances handle different tasks. Implements observable Is a thread holder.
Author
Daniel Wagenknecht
Version
2014-11-08
Definition at line 22 of file Child.h.
Constructor & Destructor Documentation
Child::Child ()
Constructor.
Default Constructor of Child instances.
Definition at line 17 of file Child.cpp.
References terminating.
Child::~Child () virtual
Destructor.
Destructor of Child instances.
Definition at line 25 of file Child.cpp.
Member Function Documentation
void Child::attachObserver (Observer * observer)
Attaches an Observer instance to Child.
Attaches the Observer instance 'observer' to this child. This method is thread safe.
Parameters
observer Observer instance to attach.
Definition at line 34 of file Child.cpp.
References observers, and obsMutex.
void Child::detachObserver (Observer * observer)
Detaches an Observer instance from Child.
Detaches the Observer instance 'observer' from this child. This method is thread safe.
Parameters
observer Observer instance to detach.
Definition at line 49 of file Child.cpp.
References observers, and obsMutex.
uint8_t Child::in_count ()
Get input count.
Returns the number of input messages of this child. This method is thread safe.
Returns
Number of pending input messages.
Definition at line 154 of file Child.cpp.
References incoming, and inMutex.
shared_ptr< Message_M2C > Child::in_pop ()
Get next pending input.
Returns the next input message of this child. This method is thread safe.
Returns
Next input message.
Definition at line 114 of file Child.cpp.
References incoming, and inMutex.
void Child::in_push (shared_ptr< Message_M2C > field)
Puts new message to input list.
Pushes the message specified by 'field' to the input list and notifies all observers about it. This method is thread safe.
Definition at line 138 of file Child.cpp.
References incoming, inMutex, and notifyObservers().
Referenced by NetworkCommunicator::print(), EvtProcessor::run(), and NetworkCommunicator::scan().
bool Child::isTerminating ()
Returns the value of the termination flag.
Returns whether this child is terminating or not.
Returns
true, if child is terminating, false otherwise.
Definition at line 93 of file Child.cpp.
References terminating.
Referenced by out_wait(), NetworkCommunicator::print(), SensorIO::run(), EvtProcessor::run(), ImgOpExecutor::run(), and NetworkCommunicator::scan().
void Child::notifyObservers ()
Notifies observers about new messages.
Notifies all observers about new pending messages. This method is thread safe.
Definition at line 62 of file Child.cpp.
References observers, and obsMutex.
Referenced by in_push(), and ImgOpExecutor::run().
uint8_t Child::out_count ()
Get output count.
Returns the number of output messages of this child. This method is thread safe.
Returns
Number of pending output messages.
Definition at line 209 of file Child.cpp.
References outgoing, and outMutex.
Referenced by NetworkCommunicator::print(), and EvtProcessor::run().
shared_ptr< Message_M2C > Child::out_pop ()
Get next pending output.
Returns the next output message of this child. This method is thread safe.
Returns
Next output message.
Definition at line 170 of file Child.cpp.
References outgoing, and outMutex.
Referenced by NetworkCommunicator::print(), and EvtProcessor::run().
void Child::out_push (shared_ptr< Message_M2C > field)
Puts new message to output list.
Pushes the message specified by 'field' to the output list. This method is thread safe.
Definition at line 193 of file Child.cpp.
References condition, outgoing, and outMutex.
Referenced by NetworkCommunicator::NetworkCommunicator(), ModuleEvent::processMsg(), and ModuleNetworking::processMsg().
void Child::out_wait ()
Wait for output messages.
Wait for new output messages.
Definition at line 222 of file Child.cpp.
References isTerminating(), and outgoing.
Referenced by NetworkCommunicator::print(), and EvtProcessor::run().
void Child::out_wait (uint32_t useconds)
Wait for output messages.
Waits for 'useconds' microseconds for new output messages.
Parameters
useconds Number of microseconds to wait for output.
Definition at line 235 of file Child.cpp.
References condition, and oWait.
virtual int Child::run () pure virtual
Implemented in EvtProcessor, ImgOpExecutor, NetworkCommunicator, and SensorIO.
Referenced by Module::run(), and Module::runChild().
void Child::term_wait ()
Waits until terminate condition is true.
Waits until terminate is called.
Definition at line 101 of file Child.cpp.
References termCondition, terminating, and termWait.
void Child::terminate ()
Sets termination flag of this child.
Sets the termination flag of this child to true.
Definition at line 81 of file Child.cpp.
References termCondition, and terminating.
Referenced by NetworkCommunicator::print(), and NetworkCommunicator::scan().
Member Data Documentation
condition_variable Child::condition private
Definition at line 56 of file Child.h.
Referenced by out_push(), and out_wait().
queue<shared_ptr<Message_M2C> > Child::incoming private
Definition at line 54 of file Child.h.
Referenced by in_count(), in_pop(), and in_push().
mutex Child::inMutex private
Definition at line 55 of file Child.h.
Referenced by in_count(), in_pop(), and in_push().
unordered_set<Observer*> Child::observers private
Definition at line 49 of file Child.h.
Referenced by attachObserver(), detachObserver(), and notifyObservers().
mutex Child::obsMutex private
Definition at line 50 of file Child.h.
Referenced by attachObserver(), detachObserver(), and notifyObservers().
queue<shared_ptr<Message_M2C> > Child::outgoing private
Definition at line 53 of file Child.h.
Referenced by out_count(), out_pop(), out_push(), and out_wait().
mutex Child::outMutex private
Definition at line 55 of file Child.h.
Referenced by out_count(), out_pop(), and out_push().
mutex Child::oWait private
Definition at line 55 of file Child.h.
Referenced by out_wait().
condition_variable Child::termCondition private
Definition at line 56 of file Child.h.
Referenced by term_wait(), and terminate().
bool Child::terminating private
Definition at line 58 of file Child.h.
Referenced by Child(), isTerminating(), term_wait(), and terminate().
mutex Child::termWait private
Definition at line 55 of file Child.h.
Referenced by term_wait().
The documentation for this class was generated from the following files:
src/Child.h
src/Child.cpp