AmberOnBoard: NetworkCommunicator Class Reference
NetworkCommunicator Class Reference
#include <NetworkCommunicator.h>
Public Member Functions
NetworkCommunicator (uint8_t commType)
Constructor.
virtual ~NetworkCommunicator ()
Destructor.
uint8_t getCommType ()
Getter for connection type.
bool appenProc (shared_ptr< FrameProcessor > proc)
Appends a frame processor.
virtual int run ()
Run method, implemented from Child.
int print ()
Prints data to network connection.
int scan ()
Scans for network input.
Public Member Functions inherited from Child
Child ()
Constructor.
virtual ~Child ()
Destructor.
void attachObserver (Observer *observer)
Attaches an Observer instance to Child.
void detachObserver (Observer *observer)
Detaches an Observer instance from Child.
void notifyObservers ()
Notifies observers about new messages.
void terminate ()
Sets termination flag of this child.
bool isTerminating ()
Returns the value of the termination flag.
void term_wait ()
Waits until terminate condition is true.
shared_ptr< Message_M2C > in_pop ()
Get next pending input.
void in_push (shared_ptr< Message_M2C > field)
Puts new message to input list.
uint8_t in_count ()
Get input count.
shared_ptr< Message_M2C > out_pop ()
Get next pending output.
void out_push (shared_ptr< Message_M2C > field)
Puts new message to output list.
uint8_t out_count ()
Get output count.
void out_wait ()
Wait for output messages.
void out_wait (uint32_t useconds)
Wait for output messages.
Private Attributes
shared_ptr< FrontProcessor > first
uint8_t commID
Detailed Description
Definition at line 27 of file NetworkCommunicator.h.
Constructor & Destructor Documentation
NetworkCommunicator::NetworkCommunicator (uint8_t commType)
Constructor.
Constructor of NetworkCommunicator instances, initializing the needed fields.
Either real time or deferred.
Definition at line 19 of file NetworkCommunicator.cpp.
References commID, first, and Child::out_push().
NetworkCommunicator::~NetworkCommunicator () virtual
Destructor.
Destructor of NetworkCommunicator instances.
Definition at line 34 of file NetworkCommunicator.cpp.
Member Function Documentation
bool NetworkCommunicator::appenProc (shared_ptr< FrameProcessor > proc)
Appends a frame processor.
Appends 'proc' to the end of the list of frame processors.
Returns
true in case of success, false otherwise.
Definition at line 52 of file NetworkCommunicator.cpp.
References first.
uint8_t NetworkCommunicator::getCommType ()
Getter for connection type.
Return the communicator type of this instance.
Returns
Connection type of this instance.
Definition at line 42 of file NetworkCommunicator.cpp.
References commID.
int NetworkCommunicator::print ()
Prints data to network connection.
Pushes messages to server connection.
Definition at line 125 of file NetworkCommunicator.cpp.
References first, Child::in_push(), Child::isTerminating(), MAX_ATTEMPT_NW_COMM, NW_OK, Child::out_count(), Child::out_pop(), Child::out_wait(), and Child::terminate().
Referenced by run().
int NetworkCommunicator::run () virtual
Run method, implemented from Child.
Runs one thread for receiving and one for transmitting data.
Implements Child.
Definition at line 172 of file NetworkCommunicator.cpp.
References first, print(), and scan().
int NetworkCommunicator::scan ()
Scans for network input.
Get messages from network interface and distribute them to the other modules.
Definition at line 84 of file NetworkCommunicator.cpp.
References first, Child::in_push(), Child::isTerminating(), MAX_ATTEMPT_NW_COMM, and Child::terminate().
Referenced by run().
Member Data Documentation
uint8_t NetworkCommunicator::commID private
Definition at line 38 of file NetworkCommunicator.h.
Referenced by getCommType(), and NetworkCommunicator().
shared_ptr<FrontProcessor> NetworkCommunicator::first private
Definition at line 37 of file NetworkCommunicator.h.
Referenced by appenProc(), NetworkCommunicator(), print(), run(), and scan().
The documentation for this class was generated from the following files:
src/nw-handling/NetworkCommunicator.h
src/nw-handling/NetworkCommunicator.cpp