AmberOnBoard: ModuleIO Class Reference
ModuleIO Class Reference
#include <ModuleIO.h>
Public Member Functions
ModuleIO ()
Constructor.
virtual ~ModuleIO ()
Destructor.
void setSensorIO (shared_ptr< SensorIO > sensors)
Sets member for sensor io.
Public Member Functions inherited from Module
Module ()
Constructor.
virtual ~Module ()
Destructor.
thread * createThread ()
int run ()
Run method of the modules main thread.
string getName ()
void update ()
Notify module about pending messages.
void terminate ()
Calls terminate on children.
bool isTerminating ()
Returns terminate status.
void addChild (shared_ptr< Child > child)
Adds a child to the list of executable children.
void deleteChild (shared_ptr< Child > child)
Deletes the child from the list of executable children.
void attachChildToMsg (shared_ptr< Child > observer, uint8_t type)
Attaches child to message type.
void detachChildFromMsg (shared_ptr< Child > observer, uint8_t type)
Detaches child from message type.
uint8_t getChildCount ()
Returns the number of children.
void runChild (uint8_t index)
Spawns a new thread on a modules child.
unordered_set< shared_ptr
< Child > >::iterator getChildrenBegin (uint8_t msgType)
Returns an iterator to first child listening to a message type.
unordered_set< shared_ptr
< Child > >::iterator getChildrenEnd (uint8_t msgType)
Returns an iterator to last child listening to a message type.
Public Member Functions inherited from Observer
Observer ()
virtual ~Observer ()
Protected Member Functions
shared_ptr< ValString > createValue (unordered_map< string, string > &data, string string)
Helper method for creating string values.
virtual uint8_t countMsgFromChildren ()
Count messages from module children.
virtual uint8_t pollMsgFromChildren ()
Polls messages from module children.
virtual shared_ptr< Message_M2M > processMsg (shared_ptr< Message_M2M >)
Processes incoming messages from message hub.
Protected Member Functions inherited from Module
bool msgAvailable ()
Checks if there are new messages available.
uint8_t pollMsgFromHub ()
Polls oldest message from hub.
Protected Attributes
shared_ptr< SensorIO > sensors
Detailed Description
Definition at line 19 of file ModuleIO.h.
Constructor & Destructor Documentation
ModuleIO::ModuleIO ()
Constructor.
Default Constructor of ModuleIO instances. Registers for messages regarding termination, commands and data acquisition.
Definition at line 16 of file ModuleIO.cpp.
References MsgHub::attachObserverToMsg(), MsgHub::getInstance(), MSG_DATA_INCOMPLETE, MSG_EVENT_INCOMPLETE, and MSG_TERM_BROADCAST.
ModuleIO::~ModuleIO () virtual
Destructor.
Destructor of ModuleIO instances.
Definition at line 28 of file ModuleIO.cpp.
Member Function Documentation
uint8_t ModuleIO::countMsgFromChildren () protected virtual
Count messages from module children.
Counts incoming messages from children. Since ModuleIO has no children creating any message, this function returns 0.
Returns
Number of child messages.
Implements Module.
Definition at line 37 of file ModuleIO.cpp.
shared_ptr< ValString > ModuleIO::createValue (unordered_map< string, string > & data, string string) protected
Helper method for creating string values.
Returns a ValiString instance based on the key 'string', which is searched in 'data'.
Parameters
data Field with key-value pairs.
string the key to get the resulting ValString for.
Returns
ValString instance with the value.
Definition at line 71 of file ModuleIO.cpp.
Referenced by processMsg().
uint8_t ModuleIO::pollMsgFromChildren () protected virtual
Polls messages from module children.
Polls incoming messages from children and counts the polled messages. This method implements child-module communication. Since ModuleIO has no children creating any message, this function returns 0.
Returns
Number of polled child messages.
Implements Module.
Definition at line 49 of file ModuleIO.cpp.
shared_ptr< Message_M2M > ModuleIO::processMsg (shared_ptr< Message_M2M > msg) protected virtual
Processes incoming messages from message hub.
Process oldest message for this module from message hub. This method implements inter-module communication. Returns the answer on the incoming message or a null pointer if no answer is needed.
Parameters
msg Incoming message from other modules.
Returns
Answer on incoming message or NULL.
Implements Module.
Definition at line 98 of file ModuleIO.cpp.
References ACC_X, ACC_Y, ACC_Z, ARG_ACC_X, ARG_ACC_Y, ARG_ACC_Z, ARG_GYRO_X, ARG_GYRO_Y, ARG_GYRO_Z, ARG_OBD_AIR_FLOW, ARG_OBD_COOL_TEMP, ARG_OBD_ENG_KM, ARG_OBD_ENG_LOAD, ARG_OBD_FUEL_LVL, ARG_OBD_FUEL_PRESS, ARG_OBD_INLET_PRESS, ARG_OBD_INLET_TEMP, ARG_OBD_RPM, ARG_OBD_SPEED, ARG_POS_E, ARG_POS_H, ARG_POS_N, createValue(), GPS_POS_HEIGHT, GPS_POS_LAT, GPS_POS_LONG, GYRO_X, GYRO_Y, GYRO_Z, MSG_DATA_COMPLETE, MSG_DATA_INCOMPLETE, MSG_EVENT_COMPLETE, MSG_EVENT_INCOMPLETE, MSG_TERM_BROADCAST, OBD_AIR_FLOW, OBD_COOL_TEMP, OBD_ENG_KM, OBD_ENG_LOAD, OBD_FUEL_LVL, OBD_FUEL_PRESS, OBD_INLET_PRESS, OBD_INLET_TEMP, OBD_RPM, OBD_SPEED, sensors, and Module::terminate().
void ModuleIO::setSensorIO (shared_ptr< SensorIO > sensors)
Sets member for sensor io.
Sets the member for sensor input/output to the one specified by 'sensors'.
Parameters
sensors Sensor io handler.
Definition at line 59 of file ModuleIO.cpp.
References sensors.
Referenced by Initializer::setUpIO().
Member Data Documentation
shared_ptr<SensorIO> ModuleIO::sensors protected
Definition at line 28 of file ModuleIO.h.
Referenced by processMsg(), and setSensorIO().
The documentation for this class was generated from the following files:
src/ModuleIO.h
src/ModuleIO.cpp