AmberOnBoard: Initializer Class Reference
Initializer Class Reference
Initialization class of the application.
#include <Initializer.h>
Public Member Functions
Initializer ()
Constructor.
virtual ~Initializer ()
Destructor.
uint8_t setup ()
Set up application modules.
void spawn ()
Spawn all module threads.
Public Member Functions inherited from Module
Module ()
Constructor.
virtual ~Module ()
Destructor.
thread * createThread ()
int run ()
Run method of the modules main thread.
string getName ()
void update ()
Notify module about pending messages.
void terminate ()
Calls terminate on children.
bool isTerminating ()
Returns terminate status.
void addChild (shared_ptr< Child > child)
Adds a child to the list of executable children.
void deleteChild (shared_ptr< Child > child)
Deletes the child from the list of executable children.
void attachChildToMsg (shared_ptr< Child > observer, uint8_t type)
Attaches child to message type.
void detachChildFromMsg (shared_ptr< Child > observer, uint8_t type)
Detaches child from message type.
uint8_t getChildCount ()
Returns the number of children.
void runChild (uint8_t index)
Spawns a new thread on a modules child.
unordered_set< shared_ptr
< Child > >::iterator getChildrenBegin (uint8_t msgType)
Returns an iterator to first child listening to a message type.
unordered_set< shared_ptr
< Child > >::iterator getChildrenEnd (uint8_t msgType)
Returns an iterator to last child listening to a message type.
Public Member Functions inherited from Observer
Observer ()
virtual ~Observer ()
Protected Member Functions
virtual uint8_t countMsgFromChildren ()
Count messages from module children.
virtual uint8_t pollMsgFromChildren ()
Polls messages from module children.
virtual shared_ptr< Message_M2M > processMsg (shared_ptr< Message_M2M >)
Processes incoming messages from message hub.
Protected Member Functions inherited from Module
bool msgAvailable ()
Checks if there are new messages available.
uint8_t pollMsgFromHub ()
Polls oldest message from hub.
Private Member Functions
uint8_t setUpIO (shared_ptr< Config > conf)
Set up input/output handling.
uint8_t setUpImgProc (shared_ptr< Config > conf)
Set up image processing.
uint8_t setUpEvtProc (shared_ptr< Config > conf)
Set up event processing.
Static Private Member Functions
static void printErr (uint8_t status, string location)
Print out error messages.
static shared_ptr
< NetworkCommunicator > createComm (string addr, string port, string iface, uint8_t commID, uint8_t devID)
Create network communicator instance.
Private Attributes
shared_ptr< Config > conf
ModuleEvent evt
ModuleIO io
ModuleImgProcessing proc
ModuleNetworking nw
Detailed Description
Initialization class of the application.
Main controlling class of the project, doing the initialization and spawning necessary module threads. Here, the configuration file is loaded and its options are distributed to all modules, as needed.
Author
Daniel Wagenknecht
Version
2014-12-25
Definition at line 54 of file Initializer.h.
Constructor & Destructor Documentation
Initializer::Initializer ()
Constructor.
Default Constructor of Initializer instances. Registers the initializer on message hub for messages to respawning threads and terminating the application.
Definition at line 17 of file Initializer.cpp.
References MsgHub::attachObserverToMsg(), MsgHub::getInstance(), MSG_RESPAWN, and MSG_TERM_BROADCAST.
Initializer::~Initializer () virtual
Destructor.
Destructor of Initializer instances.
Definition at line 28 of file Initializer.cpp.
Member Function Documentation
uint8_t Initializer::countMsgFromChildren () protected virtual
Count messages from module children.
Counts incoming messages from children. Since Initializer has no children, this function returns 0.
Returns
Number of child messages.
Implements Module.
Definition at line 439 of file Initializer.cpp.
shared_ptr< NetworkCommunicator > Initializer::createComm (string addr, string port, string iface, uint8_t commID, uint8_t devID) static private
Create network communicator instance.
Creates and sets up a network communicator instance. The instance connects over network interface 'iface' to server at 'addr' on port 'port'.
Parameters
addr Server address (IP or domain name).
port Server port to connect to.
iface Network interface to use for connection.
commID Identifier of this network communicator.
devID Id of this obu.
Returns
Shared pointer to freshly created network communicator instance..
Definition at line 549 of file Initializer.cpp.
References INIT_ERR_DEV_APPEND, INIT_ERR_DEV_SETUP, and printErr().
Referenced by processMsg().
uint8_t Initializer::pollMsgFromChildren () protected virtual
Polls messages from module children.
Polls incoming messages from children and counts the polled messages. This method implements child-module communication. Since Initializer has no children, this function does nothing and returns 0.
Returns
Number of polled child messages.
Implements Module.
Definition at line 451 of file Initializer.cpp.
void Initializer::printErr (uint8_t status, string location) static private
Print out error messages.
Prints out the error message for a given error code and location of the programm.
Parameters
status Error code.
location The affected programm part.
Definition at line 409 of file Initializer.cpp.
References INIT_ERR_DEV_APPEND, INIT_ERR_DEV_OPEN, INIT_ERR_DEV_SETUP, INIT_ERR_DEV_UNKNOWN, and INIT_ERR_LOAD.
Referenced by createComm(), processMsg(), setUpEvtProc(), setUpImgProc(), and setUpIO().
shared_ptr< Message_M2M > Initializer::processMsg (shared_ptr< Message_M2M > msg) protected virtual
Processes incoming messages from message hub.
Process oldest message for this module from message hub. This method implements inter-module communication. Returns the answer on the incoming message or a null pointer if no answer is needed.
Parameters
msg Incoming message from other modules.
Returns
Answer on incoming message or NULL.
Implements Module.
Definition at line 465 of file Initializer.cpp.
References Module::addChild(), ARG_RESPAWN_CHILD, ModuleNetworking::com_append(), conf, createComm(), Module::getChildCount(), server::iface, INIT_ERR_DEV_APPEND, INIT_ERR_LOAD, MSG_RESPAWN, MSG_TERM_BROADCAST, nw, NW_DEFERRED, NW_REALTIME, NW_TYPE_REALTIME, server::port, printErr(), Module::runChild(), server::target, and Module::terminate().
uint8_t Initializer::setup ()
Set up application modules.
Loads configuration file and distributes its options to all application modules.
Returns
Enum indicating the setup state.
Definition at line 36 of file Initializer.cpp.
References AMBER_OBU_CONF_FILE, MsgHub::appendMsg(), ARG_RESPAWN_CHILD, conf, MsgHub::getInstance(), INIT_ERR_LOAD, NW_REALTIME, setUpEvtProc(), setUpImgProc(), and setUpIO().
Referenced by main().
uint8_t Initializer::setUpEvtProc (shared_ptr< Config > conf) private
Set up event processing.
Sets up the module for event processing, based on the options in the configuration file.
Parameters
conf Configuration file instance.
Returns
Enum indicating the setup state.
Definition at line 376 of file Initializer.cpp.
References Module::addChild(), evt, ModuleEvent::evt_append(), INIT_ERR_DEV_APPEND, INIT_OK, and printErr().
Referenced by setup().
uint8_t Initializer::setUpImgProc (shared_ptr< Config > conf) private
Set up image processing.
Sets up the module for image processing, based on the options in the configuration file.
Parameters
conf Configuration file instance.
Returns
Enum indicating the setup state.
Definition at line 215 of file Initializer.cpp.
References Module::addChild(), ARG_CAM_CALC_RADIUS_AT_METER, ARG_CAM_HEIGHT, ARG_CAM_MARK_WIDTH, ARG_CAM_MARKING_SEARCH_AREA_PIX, ARG_CAM_MAX_DIST, ARG_CAM_OFFSET, ARG_CAM_PIX_TO_METER_K, ARG_CAM_THRESHOLD, ARG_CAM_VIEW_ANGLE_V, ARG_CAM_WIDTH_MULTIPLIER, ARG_JPEG_QUALITY, ARG_OP_ACTIVE, ARG_POS_X, ARG_POS_Y, ARG_SCALE, ModuleImgProcessing::exec_append(), EXEC_OK, capture::fps, capture::index, INIT_ERR_DEV_APPEND, INIT_ERR_DEV_OPEN, INIT_ERR_DEV_SETUP, INIT_ERR_DEV_UNKNOWN, INIT_ERR_LOAD, INIT_OK, PREPARE, printErr(), and proc.
Referenced by setup().
uint8_t Initializer::setUpIO (shared_ptr< Config > conf) private
Set up input/output handling.
Sets up the module for input/output handling, based on the options in the configuration file.
Parameters
conf Configuration file instance.
Returns
Enum indicating the setup state.
Definition at line 121 of file Initializer.cpp.
References Module::addChild(), i2cDev::addr, uartDev::baud, INIT_ERR_DEV_SETUP, INIT_ERR_DEV_UNKNOWN, INIT_OK, io, i2cDev::path, uartDev::path, printErr(), ModuleIO::setSensorIO(), T_ADAFRUIT, and T_MPU6050.
Referenced by setup().
void Initializer::spawn ()
Spawn all module threads.
Spawn the main modules threads and wait for them to terminate (which means the application itself should terminate).
Definition at line 87 of file Initializer.cpp.
References evt, io, nw, proc, and Module::run().
Referenced by main().
Member Data Documentation
shared_ptr<Config> Initializer::conf private
Definition at line 77 of file Initializer.h.
Referenced by processMsg(), and setup().
ModuleEvent Initializer::evt private
Definition at line 79 of file Initializer.h.
Referenced by setUpEvtProc(), and spawn().
ModuleIO Initializer::io private
Definition at line 80 of file Initializer.h.
Referenced by setUpIO(), and spawn().
ModuleNetworking Initializer::nw private
Definition at line 82 of file Initializer.h.
Referenced by processMsg(), and spawn().
ModuleImgProcessing Initializer::proc private
Definition at line 81 of file Initializer.h.
Referenced by setUpImgProc(), and spawn().
The documentation for this class was generated from the following files:
src/Initializer.h
src/Initializer.cpp