AmberOnBoard: ImgOperator Class Reference
ImgOperator Class Reference abstract
Abstract base class for image operations.
#include <ImgOperator.h>
Public Member Functions
ImgOperator (uint8_t type, uint8_t captureCount)
Constructor.
uint8_t getType ()
Getter for operator type.
virtual ~ImgOperator ()=0
Destructor.
uint8_t apply (unordered_map< string, shared_ptr< Value >> &results)
Applies operator.
virtual uint8_t getCaptureCount ()
Getter for capture count.
virtual void createCaptures (uint8_t captureCount)
Create captures.
Public Member Functions inherited from ValContainer
ValContainer ()
Constructor.
virtual ~ValContainer ()=0
Destructor.
virtual void createValue (string name, shared_ptr< Value > val)
Creates new value for this container.
void deleteKey (string name)
Deletes a value from container.
virtual uint8_t setValue (string name, const shared_ptr< Value > &val)
Sets a value in the container.
virtual uint8_t getValue (string name, shared_ptr< Value > &val)
Gets a value from container.
virtual bool initialized ()
Checks if all values are initialized.
uint8_t getValueCount ()
Gets value count.
Protected Member Functions
virtual uint8_t process (unordered_map< string, shared_ptr< Value >> &results)=0
Protected Attributes
uint8_t type
vector< string > captureIDs
Protected Attributes inherited from ValContainer
unordered_map< string,
shared_ptr< Value > > config
Detailed Description
Abstract base class for image operations.
Abstract base class for operations on opencv mat objects.
Author
Daniel Wagenknecht
Version
2014-11-12
Definition at line 39 of file ImgOperator.h.
Constructor & Destructor Documentation
ImgOperator::ImgOperator (uint8_t type, uint8_t captureCount)
Constructor.
Constructor of ImgOperator instances, setting operator type to 'type' and The number of video captures to capture count.
Parameters
type The operator type.
captureCount The number of video captures.
Definition at line 19 of file ImgOperator.cpp.
References createCaptures(), and type.
ImgOperator::~ImgOperator () pure virtual
Destructor.
Destructor of ImgOperator instances.
Definition at line 29 of file ImgOperator.cpp.
Member Function Documentation
uint8_t ImgOperator::apply (unordered_map< string, shared_ptr< Value >> & results)
Applies operator.
Checks if operator is set up properly and applies its operation. Returns status indicator.
Returns
0 in case of success, an error code otherwise.
Definition at line 78 of file ImgOperator.cpp.
References ERR_UNSET_VALUE, ValContainer::initialized(), and process().
void ImgOperator::createCaptures (uint8_t captureCount) virtual
Create captures.
Creates 'captureCount' new camera captures and creates the corresponding instances of Value for ValContainer.
Parameters
captureCount Number of video captures.
Reimplemented in OpComposite.
Definition at line 48 of file ImgOperator.cpp.
References ARG_CAPTURE, captureIDs, and ValContainer::createValue().
Referenced by ImgOperator().
uint8_t ImgOperator::getCaptureCount () virtual
Getter for capture count.
Returns the capture count of the operator.
Returns
capture count.
Reimplemented in OpComposite.
Definition at line 67 of file ImgOperator.cpp.
References captureIDs.
uint8_t ImgOperator::getType ()
Getter for operator type.
Returns the type identifier of the operator.
Returns
type identifier.
Definition at line 37 of file ImgOperator.cpp.
References type.
virtual uint8_t ImgOperator::process (unordered_map< string, shared_ptr< Value >> & results) protected pure virtual
Implemented in OpComposite, OpCurveDetection, OpPictureInPicture, and OpEncodeJPEG.
Referenced by apply().
Member Data Documentation
vector<string> ImgOperator::captureIDs protected
Definition at line 49 of file ImgOperator.h.
Referenced by createCaptures(), getCaptureCount(), OpEncodeJPEG::process(), OpPictureInPicture::process(), and OpCurveDetection::process().
uint8_t ImgOperator::type protected
Definition at line 48 of file ImgOperator.h.
Referenced by getType(), and ImgOperator().
The documentation for this class was generated from the following files:
src/img-handling/ImgOperator.h
src/img-handling/ImgOperator.cpp