AmberOnBoard: ModuleEvent Class Reference
ModuleEvent Class Reference
Application module for event propagation.
#include <ModuleEvent.h>
Public Member Functions
ModuleEvent ()
Constructor.
virtual ~ModuleEvent ()
Destructor.
uint8_t evt_append (shared_ptr< EvtProcessor > processor)
Appends event processor to list.
void evt_clear ()
Clears list of event processors.
Public Member Functions inherited from Module
Module ()
Constructor.
virtual ~Module ()
Destructor.
thread * createThread ()
int run ()
Run method of the modules main thread.
string getName ()
void update ()
Notify module about pending messages.
void terminate ()
Calls terminate on children.
bool isTerminating ()
Returns terminate status.
void addChild (shared_ptr< Child > child)
Adds a child to the list of executable children.
void deleteChild (shared_ptr< Child > child)
Deletes the child from the list of executable children.
void attachChildToMsg (shared_ptr< Child > observer, uint8_t type)
Attaches child to message type.
void detachChildFromMsg (shared_ptr< Child > observer, uint8_t type)
Detaches child from message type.
uint8_t getChildCount ()
Returns the number of children.
void runChild (uint8_t index)
Spawns a new thread on a modules child.
unordered_set< shared_ptr
< Child > >::iterator getChildrenBegin (uint8_t msgType)
Returns an iterator to first child listening to a message type.
unordered_set< shared_ptr
< Child > >::iterator getChildrenEnd (uint8_t msgType)
Returns an iterator to last child listening to a message type.
Public Member Functions inherited from Observer
Observer ()
virtual ~Observer ()
Protected Member Functions
virtual uint8_t countMsgFromChildren ()
Counts messages of children.
virtual uint8_t pollMsgFromChildren ()
Polls messages from module children.
virtual shared_ptr< Message_M2M > processMsg (shared_ptr< Message_M2M >)
Processes incoming messages from message hub.
Protected Member Functions inherited from Module
bool msgAvailable ()
Checks if there are new messages available.
uint8_t pollMsgFromHub ()
Polls oldest message from hub.
Protected Attributes
vector< shared_ptr
< EvtProcessor > > processors
Detailed Description
Application module for event propagation.
This class manages event processors and propagates their generated events.
Author
Daniel Wagenknecht
Version
2015-07-01
Definition at line 22 of file ModuleEvent.h.
Constructor & Destructor Documentation
ModuleEvent::ModuleEvent ()
Constructor.
Default Constructor of ModuleEvent instances. Registers for messages regarding termination and complete event data.
Definition at line 18 of file ModuleEvent.cpp.
References MsgHub::attachObserverToMsg(), MsgHub::getInstance(), MSG_EVENT_COMPLETE, and MSG_TERM_BROADCAST.
ModuleEvent::~ModuleEvent () virtual
Destructor.
Destructor of ModuleEvent instances.
Definition at line 29 of file ModuleEvent.cpp.
Member Function Documentation
uint8_t ModuleEvent::countMsgFromChildren () protected virtual
Counts messages of children.
Counts the pending messages of all managed EvtProcessor instances and returns the result.
Returns
Number of child messages.
Implements Module.
Definition at line 64 of file ModuleEvent.cpp.
References processors.
uint8_t ModuleEvent::evt_append (shared_ptr< EvtProcessor > processor)
Appends event processor to list.
Appends EvtProcessor specified by 'processor' to list off event processors. Returns status indicator of the operation.
Parameters
processor EvtProcessor to add.
Returns
0 in case of success, an error number otherwise.
Definition at line 39 of file ModuleEvent.cpp.
References EVT_MOD_ERR_INVALID_REFERENCE, EVT_MOD_OK, and processors.
Referenced by Initializer::setUpEvtProc().
void ModuleEvent::evt_clear ()
Clears list of event processors.
Completely clears list of EvtProcessor instances.
Definition at line 53 of file ModuleEvent.cpp.
References processors.
uint8_t ModuleEvent::pollMsgFromChildren () protected virtual
Polls messages from module children.
Polls incoming messages from children and counts the polled messages. This method implements child-module communication.
Returns
Number of polled child messages.
Implements Module.
Definition at line 86 of file ModuleEvent.cpp.
References MsgHub::appendMsg(), ARG_EVT_TYPE, ARG_IMG, ARG_POS_E, ARG_POS_N, Module::attachChildToMsg(), MsgHub::getInstance(), MSG_EVENT, MSG_EVENT_ACQUIRE, MSG_EVENT_COMPLETE, and processors.
shared_ptr< Message_M2M > ModuleEvent::processMsg (shared_ptr< Message_M2M > msg) protected virtual
Processes incoming messages from message hub.
Process oldest message for this module from message hub. This method implements inter-module communication. Returns the answer on the incoming message or a null pointer if no answer is needed.
Parameters
msg Incoming message from other modules.
Returns
Answer on incoming message or NULL.
Implements Module.
Definition at line 170 of file ModuleEvent.cpp.
References ARG_ACC_X, ARG_ACC_Y, ARG_ACC_Z, ARG_GYRO_X, ARG_GYRO_Y, ARG_GYRO_Z, ARG_IMG, ARG_OBD_AIR_FLOW, ARG_OBD_COOL_TEMP, ARG_OBD_ENG_KM, ARG_OBD_ENG_LOAD, ARG_OBD_FUEL_LVL, ARG_OBD_FUEL_PRESS, ARG_OBD_INLET_PRESS, ARG_OBD_INLET_TEMP, ARG_OBD_RPM, ARG_OBD_SPEED, ARG_POS_E, ARG_POS_H, ARG_POS_N, Module::detachChildFromMsg(), Module::getChildrenBegin(), Module::getChildrenEnd(), MSG_EVENT_COMPLETE, MSG_TERM_BROADCAST, Child::out_push(), and Module::terminate().
Member Data Documentation
vector<shared_ptr<EvtProcessor> > ModuleEvent::processors protected
Definition at line 32 of file ModuleEvent.h.
Referenced by countMsgFromChildren(), evt_append(), evt_clear(), and pollMsgFromChildren().
The documentation for this class was generated from the following files:
src/ModuleEvent.h
src/ModuleEvent.cpp