AmberOnBoard: EvtProcessor Class Reference
EvtProcessor Class Reference
Event processor.
#include <EvtProcessor.h>
Public Member Functions
EvtProcessor ()
virtual ~EvtProcessor ()
virtual int run ()
bool op_append (shared_ptr< EvtOperator > op)
Public Member Functions inherited from Child
Child ()
Constructor.
virtual ~Child ()
Destructor.
void attachObserver (Observer *observer)
Attaches an Observer instance to Child.
void detachObserver (Observer *observer)
Detaches an Observer instance from Child.
void notifyObservers ()
Notifies observers about new messages.
void terminate ()
Sets termination flag of this child.
bool isTerminating ()
Returns the value of the termination flag.
void term_wait ()
Waits until terminate condition is true.
shared_ptr< Message_M2C > in_pop ()
Get next pending input.
void in_push (shared_ptr< Message_M2C > field)
Puts new message to input list.
uint8_t in_count ()
Get input count.
shared_ptr< Message_M2C > out_pop ()
Get next pending output.
void out_push (shared_ptr< Message_M2C > field)
Puts new message to output list.
uint8_t out_count ()
Get output count.
void out_wait ()
Wait for output messages.
void out_wait (uint32_t useconds)
Wait for output messages.
Private Attributes
vector< shared_ptr< EvtOperator > > evtOperators
Detailed Description
Event processor.
This class processes values to generate events.
Author
Daniel Wagenknecht
Version
2015-01-07
Definition at line 59 of file EvtProcessor.h.
Constructor & Destructor Documentation
EvtProcessor::EvtProcessor ()
Definition at line 12 of file EvtProcessor.cpp.
EvtProcessor::~EvtProcessor () virtual
Definition at line 14 of file EvtProcessor.cpp.
Member Function Documentation
bool EvtProcessor::op_append (shared_ptr< EvtOperator > op)
Definition at line 16 of file EvtProcessor.cpp.
References evtOperators.
int EvtProcessor::run () virtual
Implements Child.
Definition at line 26 of file EvtProcessor.cpp.
References ARG_ACC_X, ARG_ACC_Y, ARG_ACC_Z, ARG_EVT_TYPE, ARG_IMG, ARG_POS_E, ARG_POS_N, EVENT_ACC, EVENT_GYRO, EVT_ACCELERATION, EVT_GYROSCOPE, evtOperators, Child::in_push(), Child::isTerminating(), Child::out_count(), Child::out_pop(), and Child::out_wait().
Member Data Documentation
vector<shared_ptr<EvtOperator> > EvtProcessor::evtOperators private
Definition at line 69 of file EvtProcessor.h.
Referenced by op_append(), and run().
The documentation for this class was generated from the following files:
src/evt-handling/EvtProcessor.h
src/evt-handling/EvtProcessor.cpp