AmberOnBoard: ProcDataFrame Class Reference
ProcDataFrame Class Reference
Data frame processor.
#include <ProcDataFrame.h>
Public Member Functions
ProcDataFrame ()
Constructor.
virtual ~ProcDataFrame ()
Destructor.
Public Member Functions inherited from FrameProcessor
FrameProcessor ()
Constructor.
FrameProcessor (bool front)
Constructor.
FrameProcessor (bool front, shared_ptr< FrameProcessor > successor)
Constructor.
virtual ~FrameProcessor ()
Destructor.
bool isFrontType ()
Getter for front value.
uint8_t transmit (shared_ptr< deque< shared_ptr< vector< uint8_t >>>> packet)
Transmit data to successor.
uint8_t receive (shared_ptr< vector< uint8_t >> packet, uint8_t *&begin, uint8_t *&end)
Receive data from successor.
void setSuccessor (shared_ptr< FrameProcessor > successor)
Setter for successor.
shared_ptr< FrameProcessor > getSuccessor ()
Getter for successor.
Public Member Functions inherited from ValContainer
ValContainer ()
Constructor.
virtual ~ValContainer ()=0
Destructor.
virtual void createValue (string name, shared_ptr< Value > val)
Creates new value for this container.
void deleteKey (string name)
Deletes a value from container.
virtual uint8_t setValue (string name, const shared_ptr< Value > &val)
Sets a value in the container.
virtual uint8_t getValue (string name, shared_ptr< Value > &val)
Gets a value from container.
virtual bool initialized ()
Checks if all values are initialized.
uint8_t getValueCount ()
Gets value count.
Protected Member Functions
virtual uint8_t forward (shared_ptr< deque< shared_ptr< vector< uint8_t >>>> packet)
Forwards packet to successor.
virtual uint8_t backward (shared_ptr< vector< uint8_t >> packet, uint8_t *&begin, uint8_t *&end)
Backwards packet from successor.
Private Member Functions
uint8_t pullFrameBegin (shared_ptr< vector< uint8_t >> packet, uint8_t *&begin, uint8_t *&end)
Searches for frame begin.
uint8_t pullPayloadLength (shared_ptr< vector< uint8_t >> packet, uint32_t &pl_Length, shared_ptr< uint8_t > &begin, shared_ptr< uint8_t > &end)
Calculates payload length.
void pullPayload (shared_ptr< vector< uint8_t >> packet, uint32_t pl_Length, uint8_t &checksum, uint8_t *&begin, uint8_t *&end)
Processes data content.
uint8_t pullFrameEnd (shared_ptr< vector< uint8_t >> packet, uint32_t pl_Length, uint8_t *&begin, uint8_t *&end)
Checks frame end.
uint8_t pullFrameBegin (shared_ptr< deque< uint8_t >> packet)
uint8_t pullPayloadLength (shared_ptr< deque< uint8_t >> packet, uint32_t *pl_Length)
uint8_t pullPayload (shared_ptr< deque< uint8_t >> packet, uint32_t pl_Length, uint8_t *checksum)
uint8_t pullFrameEnd (shared_ptr< deque< uint8_t >> packet, uint32_t pl_Length)
Private Attributes
deque< shared_ptr< vector
< uint8_t > > > pending
deque< uint8_t > tail
Additional Inherited Members
Protected Attributes inherited from ValContainer
unordered_map< string,
shared_ptr< Value > > config
Detailed Description
Data frame processor.
This class prepares data for sending by packing them into frames and unpacks data frames.
Author
Daniel Wagenknecht
Version
2015-11-21
Definition at line 23 of file ProcDataFrame.h.
Constructor & Destructor Documentation
ProcDataFrame::ProcDataFrame ()
Constructor.
Default Constructor of ProcDataFrame instances.
Definition at line 15 of file ProcDataFrame.cpp.
ProcDataFrame::~ProcDataFrame () virtual
Destructor.
Destructor of ProcDataFrame instances.
Definition at line 21 of file ProcDataFrame.cpp.
Member Function Documentation
uint8_t ProcDataFrame::backward (shared_ptr< vector< uint8_t >> packet, uint8_t *& begin, uint8_t *& end) protected virtual
Backwards packet from successor.
Backwards packet from successor and assuring frame completeness before returning. Returns a status indicator
Parameters
packet The target container of receiving process.
begin The first position to write result to.
end The end of the received data
Returns
0 in case of success, an error code otherwise.
Implements FrameProcessor.
Definition at line 89 of file ProcDataFrame.cpp.
References FrameProcessor::getSuccessor(), MAX_ATTEMPT, NW_ERR_UNKNOWN, NW_OK, pullFrameBegin(), pullFrameEnd(), pullPayload(), and tail.
uint8_t ProcDataFrame::forward (shared_ptr< deque< shared_ptr< vector< uint8_t >>>> packet) protected virtual
Forwards packet to successor.
Forwards 'packet' to successor. Returns a status indicator.
Parameters
packet The packet to send.
Returns
0 in case of success, an error code otherwise.
Implements FrameProcessor.
Definition at line 31 of file ProcDataFrame.cpp.
References CHECKSUM_INIT, FRAME_BEGIN1, FRAME_BEGIN2, FRAME_BEGIN3, FRAME_END1, FRAME_END2, FRAME_END3, FrameProcessor::getSuccessor(), and tail.
uint8_t ProcDataFrame::pullFrameBegin (shared_ptr< vector< uint8_t >> packet, uint8_t *& begin, uint8_t *& end) private
Searches for frame begin.
Searches for frame begin sequence in packet 'packet'.
Parameters
packet The target container of receiving process.
begin The first position in the data frame.
end The last position of the data.
Returns
0 in case of success, an error code otherwise.
Definition at line 206 of file ProcDataFrame.cpp.
References FRAME_BEGIN1, FRAME_BEGIN2, FRAME_BEGIN3, NW_ERR_NOT_ENOUGH_CHARS, and NW_OK.
Referenced by backward().
uint8_t ProcDataFrame::pullFrameBegin (shared_ptr< deque< uint8_t >> packet) private
uint8_t ProcDataFrame::pullFrameEnd (shared_ptr< vector< uint8_t >> packet, uint32_t pl_Length, uint8_t *& begin, uint8_t *& end) private
Checks frame end.
Searches for frame end sequence in packet 'packet' at the expected position. Returns a status indicator.
Parameters
packet The target container of receiving process.
pl_Length The payload length of this frame candidate.
begin The first position in the data frame.
end The last position of the data.
Returns
0 in case of success, an error code otherwise.
Definition at line 290 of file ProcDataFrame.cpp.
References FRAME_END1, FRAME_END2, FRAME_END3, NW_ERR_SEQUENCE_MISMATCH, and NW_OK.
Referenced by backward().
uint8_t ProcDataFrame::pullFrameEnd (shared_ptr< deque< uint8_t >> packet, uint32_t pl_Length) private
void ProcDataFrame::pullPayload (shared_ptr< vector< uint8_t >> packet, uint32_t pl_Length, uint8_t & checksum, uint8_t *& begin, uint8_t *& end) private
Processes data content.
Iterates over data in 'packet' of length 'pl_Length' and writes calculated checksum to 'checksum'.
Parameters
packet The target container of receiving process.
pl_Length The payload length to calculate the checksum for.
pl_Length The variable containing the checksum after this operation.
begin The first position in the data frame.
end The last position of the data.
Definition at line 262 of file ProcDataFrame.cpp.
Referenced by backward().
uint8_t ProcDataFrame::pullPayload (shared_ptr< deque< uint8_t >> packet, uint32_t pl_Length, uint8_t * checksum) private
uint8_t ProcDataFrame::pullPayloadLength (shared_ptr< vector< uint8_t >> packet, uint32_t & pl_Length, shared_ptr< uint8_t > & begin, shared_ptr< uint8_t > & end) private
Calculates payload length.
Calculates the payload length of data frame candidate 'packet' and writes it into pl_Length.
Parameters
packet The target container of receiving process.
pl_Length The target to write the payload length to.
begin The first position in the data frame.
end The last position of the data.
Returns
0 in case of success, an error code otherwise.
Definition at line 239 of file ProcDataFrame.cpp.
References NW_OK.
uint8_t ProcDataFrame::pullPayloadLength (shared_ptr< deque< uint8_t >> packet, uint32_t * pl_Length) private
Member Data Documentation
deque<shared_ptr<vector<uint8_t> > > ProcDataFrame::pending private
Definition at line 51 of file ProcDataFrame.h.
deque<uint8_t> ProcDataFrame::tail private
Definition at line 57 of file ProcDataFrame.h.
Referenced by backward(), and forward().
The documentation for this class was generated from the following files:
src/nw-handling/ProcDataFrame.h
src/nw-handling/ProcDataFrame.cpp