AmberOnBoard: FrameProcessor Class Reference
FrameProcessor Class Reference abstract
Abstract classes for processing network frames.
#include <FrameProcessor.h>
Public Member Functions
FrameProcessor ()
Constructor.
FrameProcessor (bool front)
Constructor.
FrameProcessor (bool front, shared_ptr< FrameProcessor > successor)
Constructor.
virtual ~FrameProcessor ()
Destructor.
bool isFrontType ()
Getter for front value.
uint8_t transmit (shared_ptr< deque< shared_ptr< vector< uint8_t >>>> packet)
Transmit data to successor.
uint8_t receive (shared_ptr< vector< uint8_t >> packet, uint8_t *&begin, uint8_t *&end)
Receive data from successor.
void setSuccessor (shared_ptr< FrameProcessor > successor)
Setter for successor.
shared_ptr< FrameProcessor > getSuccessor ()
Getter for successor.
Public Member Functions inherited from ValContainer
ValContainer ()
Constructor.
virtual ~ValContainer ()=0
Destructor.
virtual void createValue (string name, shared_ptr< Value > val)
Creates new value for this container.
void deleteKey (string name)
Deletes a value from container.
virtual uint8_t setValue (string name, const shared_ptr< Value > &val)
Sets a value in the container.
virtual uint8_t getValue (string name, shared_ptr< Value > &val)
Gets a value from container.
virtual bool initialized ()
Checks if all values are initialized.
uint8_t getValueCount ()
Gets value count.
Protected Member Functions
virtual uint8_t forward (shared_ptr< deque< shared_ptr< vector< uint8_t >>>> packet)=0
virtual uint8_t backward (shared_ptr< vector< uint8_t >> packet, uint8_t *&begin, uint8_t *&end)=0
Private Attributes
bool front
shared_ptr< FrameProcessor > successor
Additional Inherited Members
Protected Attributes inherited from ValContainer
unordered_map< string,
shared_ptr< Value > > config
Detailed Description
Abstract classes for processing network frames.
Derived instances of this classes handle data frames from networks. Each instance but the last holds a pointer to its successor to send to or receive from. By chaining processors in series, a complete network frame could be built or processed.
Author
Daniel Wagenknecht
Version
2015-11-20
Definition at line 43 of file FrameProcessor.h.
Constructor & Destructor Documentation
FrameProcessor::FrameProcessor ()
Constructor.
Default Constructor of FrameProcessor instances.
Definition at line 17 of file FrameProcessor.cpp.
FrameProcessor::FrameProcessor (bool front)
Constructor.
Constructor of FrameProcessor instances, setting it up as front or not.
Parameters
front Whether this is the first frame processor in the list or not.
Definition at line 26 of file FrameProcessor.cpp.
FrameProcessor::FrameProcessor (bool front, shared_ptr< FrameProcessor > successor)
Constructor.
Constructor of FrameProcessor instances, setting it up as front or not and setting its successor.
Parameters
front Whether this is the first frame processor in the list or not.
successor The next processor in the chain..
Definition at line 37 of file FrameProcessor.cpp.
References front, and successor.
FrameProcessor::~FrameProcessor () virtual
Destructor.
Destructor of FrameProcessor instances.
Definition at line 46 of file FrameProcessor.cpp.
Member Function Documentation
virtual uint8_t FrameProcessor::backward (shared_ptr< vector< uint8_t >> packet, uint8_t *& begin, uint8_t *& end) protected pure virtual
Implemented in FrontProcessor, NW_SocketInterface, and ProcDataFrame.
Referenced by receive().
virtual uint8_t FrameProcessor::forward (shared_ptr< deque< shared_ptr< vector< uint8_t >>>> packet) protected pure virtual
Implemented in FrontProcessor, NW_SocketInterface, and ProcDataFrame.
Referenced by transmit().
shared_ptr< FrameProcessor > FrameProcessor::getSuccessor ()
Getter for successor.
Gets the successor of this processor.
Returns
The successor of this processor.
Definition at line 74 of file FrameProcessor.cpp.
References successor.
Referenced by ProcDataFrame::backward(), FrontProcessor::backward(), ProcDataFrame::forward(), FrontProcessor::forward(), and ProcPayload::pull().
bool FrameProcessor::isFrontType ()
Getter for front value.
Returns whether this is the first processor in chain.
Returns
true if it's the first processor in chain, false otherwise.
Definition at line 54 of file FrameProcessor.cpp.
References front.
uint8_t FrameProcessor::receive (shared_ptr< vector< uint8_t >> packet, uint8_t *& begin, uint8_t *& end)
Receive data from successor.
Checks if processor is initialized and calls backward method with 'packet' and the begin and end of the data container.
Parameters
packet The container for the next packet content.
begin Begin of the data.
end End of the data.
Returns
0 in case of success, false otherwise.
Definition at line 104 of file FrameProcessor.cpp.
References backward(), ERR_UNSET_VALUE, and ValContainer::initialized().
void FrameProcessor::setSuccessor (shared_ptr< FrameProcessor > successor)
Setter for successor.
Sets the successor of this processor to 'successor'.
Parameters
successor The successor of this processor.
Definition at line 64 of file FrameProcessor.cpp.
References successor.
uint8_t FrameProcessor::transmit (shared_ptr< deque< shared_ptr< vector< uint8_t >>>> packet)
Transmit data to successor.
Checks if processor is initialized and calls forward method with 'packet'.
Parameters
packet The packet to transmit.
Returns
0 in case of success, false otherwise.
Definition at line 85 of file FrameProcessor.cpp.
References ERR_UNSET_VALUE, forward(), and ValContainer::initialized().
Referenced by ProcPayload::push().
Member Data Documentation
bool FrameProcessor::front private
Definition at line 64 of file FrameProcessor.h.
Referenced by FrameProcessor(), and isFrontType().
shared_ptr<FrameProcessor> FrameProcessor::successor private
Definition at line 65 of file FrameProcessor.h.
Referenced by FrameProcessor(), getSuccessor(), and setSuccessor().
The documentation for this class was generated from the following files:
src/nw-handling/FrameProcessor.h
src/nw-handling/FrameProcessor.cpp