AmberOnBoard: ValContainer Class Reference
ValContainer Class Reference abstract
Container class for storing values.
#include <ValContainer.h>
Public Member Functions
ValContainer ()
Constructor.
virtual ~ValContainer ()=0
Destructor.
virtual void createValue (string name, shared_ptr< Value > val)
Creates new value for this container.
void deleteKey (string name)
Deletes a value from container.
virtual uint8_t setValue (string name, const shared_ptr< Value > &val)
Sets a value in the container.
virtual uint8_t getValue (string name, shared_ptr< Value > &val)
Gets a value from container.
virtual bool initialized ()
Checks if all values are initialized.
uint8_t getValueCount ()
Gets value count.
Protected Attributes
unordered_map< string,
shared_ptr< Value > > config
Detailed Description
Container class for storing values.
This class stores a variable number of different data types, encapsulated as Value objects.
Author
Daniel Wagenknecht
Version
2014-11-14
Definition at line 28 of file ValContainer.h.
Constructor & Destructor Documentation
ValContainer::ValContainer ()
Constructor.
Default Constructor of value container instances.
Definition at line 15 of file ValContainer.cpp.
ValContainer::~ValContainer () pure virtual
Destructor.
Destructor of value container instances.
Definition at line 21 of file ValContainer.cpp.
Member Function Documentation
void ValContainer::createValue (string name, shared_ptr< Value > value) virtual
Creates new value for this container.
Creates a new Value of the type specified in 'value', accessible through key 'name'.
Parameters
name Name to identify the value.
value Instance to use as initial value.
Definition at line 30 of file ValContainer.cpp.
References config.
Referenced by ImgOperator::createCaptures(), M2C_Command::M2C_Command(), M2C_DataSet::M2C_DataSet(), M2C_Event::M2C_Event(), M2C_EventDataSet::M2C_EventDataSet(), M2C_TerminalInput::M2C_TerminalInput(), M2C_TerminalOutput::M2C_TerminalOutput(), M2M_Command::M2M_Command(), M2M_DataSet::M2M_DataSet(), M2M_Event::M2M_Event(), M2M_EventDataSet::M2M_EventDataSet(), M2M_Respawn::M2M_Respawn(), M2M_TerminalInput::M2M_TerminalInput(), OpCurveDetection::OpCurveDetection(), OpEncodeJPEG::OpEncodeJPEG(), OpPictureInPicture::OpPictureInPicture(), and ImgOpExecutor::setResult().
void ValContainer::deleteKey (string name)
Deletes a value from container.
Deletes the value with key 'name' from container.
Parameters
name Name to identify the value.
Definition at line 40 of file ValContainer.cpp.
References config.
Referenced by ImgOpExecutor::setResult().
uint8_t ValContainer::getValue (string name, shared_ptr< Value > & val) virtual
Gets a value from container.
Writes the Value instance specified by 'name' to 'val'. Returns a status indicator.
Parameters
name Name to identify the value.
val Instance which after this operation holds the value.
Returns
0 in case of success, an error code otherwise.
Reimplemented in OpComposite.
Definition at line 152 of file ValContainer.cpp.
References config, ERR_NO_SUCH_KEY, ERR_UNSET_VALUE, and OK.
Referenced by ImgOpExecutor::getResult(), OpCurveDetection::initialize(), M2C_DataSet::M2C_DataSet(), OpEncodeJPEG::process(), OpPictureInPicture::process(), and OpCurveDetection::process().
uint8_t ValContainer::getValueCount ()
Gets value count.
Returns the number of values currently stored in this container.
Returns
number of values in this container.
Definition at line 198 of file ValContainer.cpp.
References config.
bool ValContainer::initialized () virtual
Checks if all values are initialized.
Iterates through all values and checks if they are initialized. Returns the result of that check.
Returns
true if all values are initialized, false otherwise.
Reimplemented in OpComposite.
Definition at line 180 of file ValContainer.cpp.
References config.
Referenced by ImgOperator::apply(), OpCurveDetection::initialize(), OpCurveDetection::OpCurveDetection(), OpCurveDetection::process(), FrameProcessor::receive(), and FrameProcessor::transmit().
uint8_t ValContainer::setValue (string name, const shared_ptr< Value > & val) virtual
Sets a value in the container.
Sets the value specified by 'name' to the Value instance specified by 'val'. Returns a status indicator for this operation.
Parameters
name Name to identify the value.
value New value instance.
Returns
0 in case of success, an error code otherwise.
Reimplemented in OpComposite.
Definition at line 53 of file ValContainer.cpp.
References config, ERR_NO_SUCH_KEY, ERR_TYPE_MISMATCH, ERR_UNKNOWN, OK, ValDouble::setValue(), ValMat::setValue(), ValInt::setValue(), ValString::setValue(), ValVectorUChar::setValue(), VAL_DOUBLE, VAL_INT, VAL_MAT, VAL_STRING, and VAL_UCHAR_VECTOR.
Referenced by ImgOpExecutor::setResult().
Member Data Documentation
unordered_map<string,shared_ptr<Value> > ValContainer::config protected
Definition at line 39 of file ValContainer.h.
Referenced by createValue(), deleteKey(), getValue(), getValueCount(), initialized(), and setValue().
The documentation for this class was generated from the following files:
src/ValContainer.h
src/ValContainer.cpp