AmberOnBoard: IOfile Class Reference
IOfile Class Reference
Gneral class for file handling.
#include <IOfile.h>
Public Member Functions
IOfile (string path)
Constructor.
virtual ~IOfile ()
Destructor.
bool exists ()
Checks if file exists.
string getPath ()
Getter for file path.
virtual uint8_t open (uint8_t type, bool force=false)
Open file.
virtual bool isOpen ()
Checks if file is open.
virtual uint8_t setup ()
File setup.
virtual uint8_t reset ()
File reset.
virtual uint8_t close ()
Close file.
Public Member Functions inherited from IOparent
IOparent ()
Constructor.
virtual ~IOparent ()
Destructor.
void setActive (bool active)
Sets activity status.
bool isActive ()
Check instance activity.
uint8_t readSafe (string &input, uint8_t delim)
Safely reads from input.
uint8_t readOpen (string &input, uint8_t delim)
Opens input and reads from it.
uint8_t read (string &input, uint8_t delim)
Read from input.
uint8_t writeSafe (string output)
Safely writes string to output.
uint8_t write (string output)
Writes string to output.
uint8_t appendSafe (string output)
Safely appends string to output.
uint8_t appendOpen (string output)
Opens output in append mode and writes to it.
uint8_t append (string output)
Opens output in append mode and writes to it.
Protected Member Functions
virtual uint8_t getChar ()
Read byte.
virtual uint8_t putString (string &output)
Writes string to file.
Private Attributes
string path
FILE * file
Detailed Description
Gneral class for file handling.
This class represents a file in file system and offers methods for access.
Author
Daniel Wagenknecht
Version
2014-12-25
Definition at line 22 of file IOfile.h.
Constructor & Destructor Documentation
IOfile::IOfile (string path)
Constructor.
Constructor of IOfile instances, using 'path' as file path.
Parameters
path Path to configuration file
Definition at line 17 of file IOfile.cpp.
References file, and path.
IOfile::~IOfile () virtual
Destructor.
Destructor of IOfile instances.
Definition at line 26 of file IOfile.cpp.
Member Function Documentation
uint8_t IOfile::close () virtual
Close file.
Closes the file, if it is open. Returns status indicator
Returns
0 in case of success, an error code otherwise.
Implements IOparent.
Definition at line 135 of file IOfile.cpp.
References file, IO_ERR_CLOSE, IO_OK, isOpen(), and IOparent::setActive().
Referenced by open().
bool IOfile::exists ()
Checks if file exists.
Returns whether the specified file exists or not.
Returns
true if file exists, false otherwise.
Definition at line 34 of file IOfile.cpp.
References path.
Referenced by Config::load().
uint8_t IOfile::getChar () protected virtual
Read byte.
Reads a single byte from file and returns it.
Returns
Next character in file.
Implements IOparent.
Definition at line 162 of file IOfile.cpp.
References file.
string IOfile::getPath ()
Getter for file path.
Returns the file path of this instance.
Returns
current file path.
Definition at line 47 of file IOfile.cpp.
References path.
Referenced by Config::load().
bool IOfile::isOpen () virtual
Checks if file is open.
Returns whether the specified file is already opened by this instance or not.
Returns
true if file is open, false otherwise.
Implements IOparent.
Definition at line 102 of file IOfile.cpp.
References file.
Referenced by close(), and open().
uint8_t IOfile::open (uint8_t type, bool force = false) virtual
Open file.
Opens the file in mode 'type'. If 'force' is true and the file is alread open, a reopen is forced. Type must be one of: OPEN_W = for writing Open_R = OPEN_A = for appending Returns status indicator.
Parameters
type Mode of opening.
force flag (true for forcing reopen).
Returns
0 in case of success, an error code otherwise.
Implements IOparent.
Definition at line 63 of file IOfile.cpp.
References close(), file, IO_ERR_OPEN, IO_OK, isOpen(), OPEN_A, OPEN_R, OPEN_W, path, and IOparent::setActive().
uint8_t IOfile::putString (string & output) protected virtual
Writes string to file.
Writes all bytes of 'output' to the file. Returns status indicator.
Returns
0 in case of success, an error code otherwise.
Implements IOparent.
Definition at line 176 of file IOfile.cpp.
References file, IO_ERR_WRITE, and IO_OK.
uint8_t IOfile::reset () virtual
File reset.
Does not affect 'real' files.
Implements IOparent.
Definition at line 122 of file IOfile.cpp.
References IO_OK.
uint8_t IOfile::setup () virtual
File setup.
Does not affect 'real' files.
Implements IOparent.
Definition at line 112 of file IOfile.cpp.
References IO_OK.
Member Data Documentation
FILE* IOfile::file private
Definition at line 51 of file IOfile.h.
Referenced by close(), getChar(), IOfile(), isOpen(), open(), and putString().
string IOfile::path private
Definition at line 48 of file IOfile.h.
Referenced by exists(), getPath(), IOfile(), and open().
The documentation for this class was generated from the following files:
src/io-handling/instances/IOfile.h
src/io-handling/instances/IOfile.cpp