AmberOnBoard: ModuleImgProcessing Class Reference
ModuleImgProcessing Class Reference
Application module for image processing.
#include <ModuleImgProcessing.h>
Public Member Functions
ModuleImgProcessing ()
Constructor.
virtual ~ModuleImgProcessing ()
Destructor.
uint8_t exec_append (string key, shared_ptr< ImgOpExecutor > executor)
Appends image op executor processor to list.
uint8_t exec_delete (string key)
Deletes an element from list of image op executors.
void exec_clear ()
Clears list of image op executors.
Public Member Functions inherited from Module
Module ()
Constructor.
virtual ~Module ()
Destructor.
thread * createThread ()
int run ()
Run method of the modules main thread.
string getName ()
void update ()
Notify module about pending messages.
void terminate ()
Calls terminate on children.
bool isTerminating ()
Returns terminate status.
void addChild (shared_ptr< Child > child)
Adds a child to the list of executable children.
void deleteChild (shared_ptr< Child > child)
Deletes the child from the list of executable children.
void attachChildToMsg (shared_ptr< Child > observer, uint8_t type)
Attaches child to message type.
void detachChildFromMsg (shared_ptr< Child > observer, uint8_t type)
Detaches child from message type.
uint8_t getChildCount ()
Returns the number of children.
void runChild (uint8_t index)
Spawns a new thread on a modules child.
unordered_set< shared_ptr
< Child > >::iterator getChildrenBegin (uint8_t msgType)
Returns an iterator to first child listening to a message type.
unordered_set< shared_ptr
< Child > >::iterator getChildrenEnd (uint8_t msgType)
Returns an iterator to last child listening to a message type.
Public Member Functions inherited from Observer
Observer ()
virtual ~Observer ()
Protected Member Functions
virtual uint8_t countMsgFromChildren ()
Counts messages of children.
virtual uint8_t pollMsgFromChildren ()
Polls messages from module children.
virtual shared_ptr< Message_M2M > processMsg (shared_ptr< Message_M2M >)
Processes incoming messages from message hub.
Protected Member Functions inherited from Module
bool msgAvailable ()
Checks if there are new messages available.
uint8_t pollMsgFromHub ()
Polls oldest message from hub.
Protected Attributes
unordered_map< string,
shared_ptr< ImgOpExecutor > > executors
Detailed Description
Application module for image processing.
Application module for input / output handling.
This class manages image processors.
Author
Daniel Wagenknecht
Version
2014-11-08
This class manages input / output handling and sensor communication.
Author
Daniel Wagenknecht
Version
2014-11-08
Definition at line 26 of file ModuleImgProcessing.h.
Constructor & Destructor Documentation
ModuleImgProcessing::ModuleImgProcessing ()
Constructor.
Default Constructor of ModuleImgProcessing instances. Registers for messages regarding termination, commands and data acquisition.
Definition at line 16 of file ModuleImgProcessing.cpp.
References MsgHub::attachObserverToMsg(), MsgHub::getInstance(), MSG_COMMAND, MSG_DATA_ACQUIRED, MSG_EVENT_ACQUIRE, and MSG_TERM_BROADCAST.
ModuleImgProcessing::~ModuleImgProcessing () virtual
Destructor.
Destructor of ModuleImgProcessing instances.
Definition at line 30 of file ModuleImgProcessing.cpp.
Member Function Documentation
uint8_t ModuleImgProcessing::countMsgFromChildren () protected virtual
Counts messages of children.
Counts the pending messages of all managed ImgOpExecutor instances and returns the result.
Returns
Number of child messages.
Implements Module.
Definition at line 84 of file ModuleImgProcessing.cpp.
uint8_t ModuleImgProcessing::exec_append (string key, shared_ptr< ImgOpExecutor > executor)
Appends image op executor processor to list.
Appends ImgOpExecutor specified by 'executor' to list of image op executors. Returns status indicator of the operation.
Parameters
executor ImgOpExecutor to add.
Returns
0 in case of success, an error number otherwise.
Definition at line 40 of file ModuleImgProcessing.cpp.
References executors, IMG_PROC_ERR_INVALID_REFERENCE, IMG_PROC_ERR_UNKNOWN, and IMG_PROC_OK.
Referenced by Initializer::setUpImgProc().
void ModuleImgProcessing::exec_clear ()
Clears list of image op executors.
Completely clears list of image op executor instances.
Definition at line 72 of file ModuleImgProcessing.cpp.
References executors.
uint8_t ModuleImgProcessing::exec_delete (string key)
Deletes an element from list of image op executors.
Deletes the element specified by 'key' from list of executors.
Parameters
key The executors key.
Returns
0 in case of success, an error number otherwise.
Definition at line 58 of file ModuleImgProcessing.cpp.
References executors, IMG_PROC_ERR_UNKNOWN, and IMG_PROC_OK.
uint8_t ModuleImgProcessing::pollMsgFromChildren () protected virtual
Polls messages from module children.
Polls incoming messages from children and counts the polled messages. This method implements child-module communication.
Returns
Number of polled child messages.
Implements Module.
Definition at line 97 of file ModuleImgProcessing.cpp.
shared_ptr< Message_M2M > ModuleImgProcessing::processMsg (shared_ptr< Message_M2M > msg) protected virtual
Processes incoming messages from message hub.
Process oldest message for this module from message hub. This method implements inter-module communication. Returns the answer on the incoming message or a null pointer if no answer is needed.
Parameters
msg Incoming message from other modules.
Returns
Answer on incoming message or NULL.
Implements Module.
Definition at line 113 of file ModuleImgProcessing.cpp.
References ARG_COMMAND_TYPE, ARG_IMG, ARG_OP_ACTIVE, CMD_CURVE_ACTIVE, CMD_CURVE_INACTIVE, CMD_SWAP_CAM, executors, MSG_COMMAND, MSG_DATA_ACQUIRED, MSG_EVENT_ACQUIRE, MSG_TERM_BROADCAST, PREPARE, RES_ENCODED_JPEG, ValVectorUChar::setValue(), and Module::terminate().
Member Data Documentation
unordered_map<string, shared_ptr<ImgOpExecutor> > ModuleImgProcessing::executors protected
Definition at line 36 of file ModuleImgProcessing.h.
Referenced by exec_append(), exec_clear(), exec_delete(), and processMsg().
The documentation for this class was generated from the following files:
src/ModuleImgProcessing.h
src/ModuleImgProcessing.cpp