AmberOnBoard: NmeaParser Class Reference
NmeaParser Class Reference
#include <NmeaParser.h>
Static Public Member Functions
static uint8_t parseGGA (string source, gga &dataset)
Parse NMEA output.
Private Member Functions
NmeaParser ()
virtual ~NmeaParser ()
Static Private Member Functions
static void tokenize (string source, vector< string > &target, char delim)
Helper method for tokenizing.
Detailed Description
Definition at line 40 of file NmeaParser.h.
Constructor & Destructor Documentation
NmeaParser::NmeaParser () private
Definition at line 11 of file NmeaParser.cpp.
NmeaParser::~NmeaParser () private virtual
Definition at line 12 of file NmeaParser.cpp.
Member Function Documentation
uint8_t NmeaParser::parseGGA (string source, gga & dataset) static
Parse NMEA output.
Parses GPGGA sentence 'source' and writes results into 'dataset'. Returns status indicator.
Parameters
source Sentence to parse.
dataset target to write to.
Returns
0 in case of success, an error code otherwise.
Definition at line 23 of file NmeaParser.cpp.
References gga::dgpsAge, gga::dgpsRef, gga::hdop, gga::height, gga::latVal, gga::longVal, PARSE_ERR_INCOMPLETE, PARSE_ERR_INVALID, PARSE_OK, gga::quality, gga::satCnt, gga::sepVal, tokenize(), and gga::utc.
Referenced by GpsAdafruit::run().
void NmeaParser::tokenize (string source, vector< string > & target, char delim) static private
Helper method for tokenizing.
Tokenizes string 'source' by delimiter 'delim' and writes all tokens to 'target'
Parameters
source Source string.
target Target vector.
delim Delimiter for tokenizing.
Definition at line 61 of file NmeaParser.cpp.
Referenced by parseGGA().
The documentation for this class was generated from the following files:
src/io-handling/NmeaParser.h
src/io-handling/NmeaParser.cpp