AmberOnBoard: GpsAdafruit Class Reference
GpsAdafruit Class Reference
Device class for adafruit receiver.
#include <GpsAdafruit.h>
Public Member Functions
GpsAdafruit (string path, uint32_t baud)
Constructor.
virtual ~GpsAdafruit ()
Destructor.
virtual int run ()
Thread run method.
virtual void getValues (unordered_map< string, string > &values)
Get results.
uint8_t initialize ()
Initialize device.
uint8_t setUpdate (uint16_t interval)
Output rate.
uint8_t setBaud (uint32_t baud)
Set baud rate to use.
uint8_t setNMEA (uint8_t gll, uint8_t rmc, uint8_t vtg, uint8_t gga, uint8_t gsa, uint8_t gsv)
Set NMEA output.
uint8_t printFrame (uint16_t msgType, string content)
Write frame to serial device.
uint8_t getChecksum (string source)
Generate checksum for string.
Public Member Functions inherited from Device
Device ()
Constructor.
virtual ~Device ()
Destructor.
void terminate ()
Sets termination flag.
bool isTerminating ()
Get termination value.
Private Attributes
IOserial device
unordered_map< string, string > values
mutex rw_mutex
Additional Inherited Members
Static Protected Member Functions inherited from Device
static void addValue (unordered_map< string, string > &values, string key, string value)
Add value to results.
Detailed Description
Device class for adafruit receiver.
Concrete device class for adafruit gps receiver.
Author
Daniel Wagenknecht
Version
2014-12-21
Definition at line 47 of file GpsAdafruit.h.
Constructor & Destructor Documentation
GpsAdafruit::GpsAdafruit (string path, uint32_t baud)
Constructor.
Constructor of GpsAdafruit instances, using 'path' as device path and setting baud rate to 'baud'.
Parameters
path Path to device in file system.
baud Baud rate to use
Definition at line 18 of file GpsAdafruit.cpp.
GpsAdafruit::~GpsAdafruit () virtual
Destructor.
Destructor of GpsAdafruit instances. Closes the corresponding serial port.
Definition at line 25 of file GpsAdafruit.cpp.
References IOserial::close(), and device.
Member Function Documentation
uint8_t GpsAdafruit::getChecksum (string source)
Generate checksum for string.
Returns the adafruit checksum for string 'source'. Returns status indicator.
Parameters
source String to calculate Checksum for.
Returns
Checksum of the string.
Definition at line 154 of file GpsAdafruit.cpp.
Referenced by printFrame().
void GpsAdafruit::getValues (unordered_map< string, string > & values) virtual
Get results.
Writes the current gps results into 'values'.
Parameters
values The target to write the results to.
Implements Device.
Definition at line 70 of file GpsAdafruit.cpp.
References Device::addValue(), GPS_POS_HEIGHT, GPS_POS_LAT, GPS_POS_LONG, and rw_mutex.
uint8_t GpsAdafruit::initialize ()
Initialize device.
Initializes and sets up gps device. Returns status indicator.
Returns
0 in case of success, an error code otherwise.
Definition at line 99 of file GpsAdafruit.cpp.
References AF_ERR_OPEN, AF_OK, device, IOserial::open(), OPEN_W, setNMEA(), and setUpdate().
uint8_t GpsAdafruit::printFrame (uint16_t msgType, string content)
Write frame to serial device.
Generates adafruit protocol compatible data frame from 'content' with id 'msgType' And writes it to serial port.. Returns status indicator.
Parameters
msgType The message id.
content The data to write.
Returns
0 in case of success, an error code otherwise.
Definition at line 128 of file GpsAdafruit.cpp.
References AF_OK, IOparent::appendOpen(), device, and getChecksum().
Referenced by setBaud(), setNMEA(), and setUpdate().
int GpsAdafruit::run () virtual
Thread run method.
Implementation of Device's virtual run method. Runs until terminate is called or the device gets inactive.
Implements Device.
Definition at line 34 of file GpsAdafruit.cpp.
References Device::addValue(), device, GPS_POS_HEIGHT, GPS_POS_LAT, GPS_POS_LONG, gga::height, gga::hUnit, IOparent::isActive(), Device::isTerminating(), gga::latNS, gga::latVal, gga::longEW, gga::longVal, NmeaParser::parseGGA(), IOparent::readOpen(), rw_mutex, and values.
uint8_t GpsAdafruit::setBaud (uint32_t baud)
Set baud rate to use.
Writes baud rate frame for 'baud' to device and sets serial port baud rate. Returns status indicator.
Parameters
baud The new baud rate
Returns
0 in case of success, an error code otherwise.
Definition at line 175 of file GpsAdafruit.cpp.
References AF_ERR_INVALID_BAUD, device, PMTK_SET_NMEA_BAUDRATE, printFrame(), and IOserial::setBaud().
uint8_t GpsAdafruit::setNMEA (uint8_t gll, uint8_t rmc, uint8_t vtg, uint8_t gga, uint8_t gsa, uint8_t gsv)
Set NMEA output.
Sets up which NMEA sentences to use in which interval. Returns status indicator.
Parameters
gll Interval for GPGLL message.
rmc Interval for GPRMC message.
vtg Interval for GPVTG message.
gga Interval for GPGGA message.
gsa Interval for GPGSA message.
gsv Interval for GPGSV message.
Returns
0 in case of success, an error code otherwise.
Definition at line 208 of file GpsAdafruit.cpp.
References AF_ERR_INVALID_NMEA_UPDATE, PMTK_API_SET_NMEA_OUTPUT, and printFrame().
Referenced by initialize().
uint8_t GpsAdafruit::setUpdate (uint16_t interval)
Output rate.
Sets NMEA sentence output interval. Returns status indicator.
Parameters
interval New output interval.
Returns
0 in case of success, an error code otherwise.
Definition at line 250 of file GpsAdafruit.cpp.
References AF_ERR_INVALID_FIX_INTERVAL, PMTK_SET_NMEA_UPDATERATE, and printFrame().
Referenced by initialize().
Member Data Documentation
IOserial GpsAdafruit::device private
Definition at line 77 of file GpsAdafruit.h.
Referenced by initialize(), printFrame(), run(), setBaud(), and ~GpsAdafruit().
mutex GpsAdafruit::rw_mutex private
Definition at line 83 of file GpsAdafruit.h.
Referenced by getValues(), and run().
unordered_map<string, string> GpsAdafruit::values private
Definition at line 80 of file GpsAdafruit.h.
Referenced by run().
The documentation for this class was generated from the following files:
src/io-handling/GpsAdafruit.h
src/io-handling/GpsAdafruit.cpp