AmberOnBoard: ProcPayload Class Reference
ProcPayload Class Reference
Payload processor.
#include <ProcPayload.h>
Public Member Functions
ProcPayload (uint8_t devID)
Constructor.
virtual ~ProcPayload ()
Destructor.
virtual uint8_t push (shared_ptr< Message_M2C > output)
Pushes output to chain of transmission..
virtual uint8_t pull (shared_ptr< Message_M2C > &input)
Pulls input from chain of reception.
Public Member Functions inherited from FrontProcessor
FrontProcessor ()
Constructor.
FrontProcessor (shared_ptr< FrameProcessor > successor)
Constructor.
virtual ~FrontProcessor ()=0
Destructor.
Public Member Functions inherited from FrameProcessor
FrameProcessor ()
Constructor.
FrameProcessor (bool front)
Constructor.
FrameProcessor (bool front, shared_ptr< FrameProcessor > successor)
Constructor.
virtual ~FrameProcessor ()
Destructor.
bool isFrontType ()
Getter for front value.
uint8_t transmit (shared_ptr< deque< shared_ptr< vector< uint8_t >>>> packet)
Transmit data to successor.
uint8_t receive (shared_ptr< vector< uint8_t >> packet, uint8_t *&begin, uint8_t *&end)
Receive data from successor.
void setSuccessor (shared_ptr< FrameProcessor > successor)
Setter for successor.
shared_ptr< FrameProcessor > getSuccessor ()
Getter for successor.
Public Member Functions inherited from ValContainer
ValContainer ()
Constructor.
virtual ~ValContainer ()=0
Destructor.
virtual void createValue (string name, shared_ptr< Value > val)
Creates new value for this container.
void deleteKey (string name)
Deletes a value from container.
virtual uint8_t setValue (string name, const shared_ptr< Value > &val)
Sets a value in the container.
virtual uint8_t getValue (string name, shared_ptr< Value > &val)
Gets a value from container.
virtual bool initialized ()
Checks if all values are initialized.
uint8_t getValueCount ()
Gets value count.
Private Member Functions
uint8_t packRegister (queue< shared_ptr< deque< shared_ptr< vector< uint8_t >>>>> &packets)
Packs frame for obu registration.
uint8_t packAcquiredData (queue< shared_ptr< deque< shared_ptr< vector< uint8_t >>>>> &packets, shared_ptr< M2C_DataSet > data)
Packs frame for telemetry and image stream.
uint8_t packEvent (queue< shared_ptr< deque< shared_ptr< vector< uint8_t >>>>> &packets, shared_ptr< M2C_Event > data)
Packs event frame.
void insertTelemetry (shared_ptr< vector< uint8_t >> &packet, string &data, uint8_t identifier)
Helper method to insert telemetry data.
uint8_t unpackAcquiredData (shared_ptr< M2C_DataAcquired > &data, shared_ptr< vector< uint8_t >> &packet, uint8_t *&begin, uint8_t *&end)
Unpacks acquired data frame.
uint8_t unpackCommand (shared_ptr< M2C_Command > &data, shared_ptr< vector< uint8_t >> &packet, uint8_t *&begin, uint8_t *&end)
Unpacks command frame.
Private Attributes
uint8_t devID
timeval step1
timeval step2
Additional Inherited Members
Protected Member Functions inherited from FrontProcessor
virtual uint8_t forward (shared_ptr< deque< shared_ptr< vector< uint8_t >>>> packet)
Transmit data to successor.
virtual uint8_t backward (shared_ptr< vector< uint8_t >> packet, uint8_t *&begin, uint8_t *&end)
Receive data from successor.
Protected Attributes inherited from ValContainer
unordered_map< string,
shared_ptr< Value > > config
Detailed Description
Payload processor.
This class interprets the received data and generates messages for the network module.
Author
Daniel Wagenknecht
Version
2015-11-21
Definition at line 59 of file ProcPayload.h.
Constructor & Destructor Documentation
ProcPayload::ProcPayload (uint8_t devID)
Constructor.
Constructor of ProcPayload instances, initializing the needed fields.
Parameters
devID Device ID of this obu, which gets sent in each frame.
Definition at line 17 of file ProcPayload.cpp.
References devID.
ProcPayload::~ProcPayload () virtual
Destructor.
Destructor of ProcPayload instances.
Definition at line 25 of file ProcPayload.cpp.
Member Function Documentation
void ProcPayload::insertTelemetry (shared_ptr< vector< uint8_t >> & packet, string & data, uint8_t identifier) private
Helper method to insert telemetry data.
Writes data from 'data' with its length and the identifier 'identifier' to 'packet'.
Parameters
packet The data container to write the frame to.
data The telemetry string
data The data identifier.
Definition at line 359 of file ProcPayload.cpp.
Referenced by packAcquiredData(), and packEvent().
uint8_t ProcPayload::packAcquiredData (queue< shared_ptr< deque< shared_ptr< vector< uint8_t >>>>> & packets, shared_ptr< M2C_DataSet > data) private
Packs frame for telemetry and image stream.
Builds frame for telemetry and image transmission, using data 'data' and writing it to 'packets.' Returns status indicator.
Parameters
packets The data container to write the frame to.
data The content of the frame.
Returns
0 in case of success, an error code otherwise.
Definition at line 147 of file ProcPayload.cpp.
References ARG_ACC_X, ARG_ACC_Y, ARG_ACC_Z, ARG_GYRO_X, ARG_GYRO_Y, ARG_GYRO_Z, ARG_IMG, ARG_OBD_AIR_FLOW, ARG_OBD_COOL_TEMP, ARG_OBD_ENG_KM, ARG_OBD_ENG_LOAD, ARG_OBD_FUEL_LVL, ARG_OBD_FUEL_PRESS, ARG_OBD_INLET_PRESS, ARG_OBD_INLET_TEMP, ARG_OBD_RPM, ARG_OBD_SPEED, ARG_POS_E, ARG_POS_H, ARG_POS_N, DATA_TYPE_IMG, DATA_TYPE_TELEMETRY, devID, FIELD_TYPE_ACC_X, FIELD_TYPE_ACC_Y, FIELD_TYPE_ACC_Z, FIELD_TYPE_GYRO_X, FIELD_TYPE_GYRO_Y, FIELD_TYPE_GYRO_Z, FIELD_TYPE_OBD_AIR_FLOW, FIELD_TYPE_OBD_COOL_TEMP, FIELD_TYPE_OBD_ENG_KM, FIELD_TYPE_OBD_ENG_LOAD, FIELD_TYPE_OBD_FUEL_LVL, FIELD_TYPE_OBD_FUEL_PRESS, FIELD_TYPE_OBD_INLET_PRESS, FIELD_TYPE_OBD_INLET_TEMP, FIELD_TYPE_OBD_RPM, FIELD_TYPE_OBD_SPEED, FIELD_TYPE_POS_E, FIELD_TYPE_POS_N, FIELD_TYPE_POS_T, insertTelemetry(), MSG_ID_IMAGE, MSG_ID_TELEMETRY, NW_ERR_ARGUMENT, NW_OK, OK, and PAYLOAD_SIZE.
Referenced by push().
uint8_t ProcPayload::packEvent (queue< shared_ptr< deque< shared_ptr< vector< uint8_t >>>>> & packets, shared_ptr< M2C_Event > data) private
Packs event frame.
Builds frame for event signals, using data 'data' and writing it to 'packets.' Returns status indicator.
Parameters
packets The data container to write the frame to.
data The content of the frame.
Returns
0 in case of success, an error code otherwise.
Definition at line 378 of file ProcPayload.cpp.
References ARG_EVT_TYPE, ARG_IMG, ARG_POS_E, ARG_POS_N, DATA_TYPE_EVENT_DATA, DATA_TYPE_IMG, devID, EVENT_ACC, EVENT_GYRO, EVENT_ID_ACC, EVENT_ID_GYRO, FIELD_TYPE_POS_E, FIELD_TYPE_POS_N, FIELD_TYPE_POS_T, insertTelemetry(), MSG_ID_EVENT, NW_ERR_ARGUMENT, NW_ERR_UNKNOWN, NW_OK, OK, and PAYLOAD_SIZE.
Referenced by push().
uint8_t ProcPayload::packRegister (queue< shared_ptr< deque< shared_ptr< vector< uint8_t >>>>> & packets) private
Packs frame for obu registration.
Builds frame for obu registration and writes it to 'packets'. Returns status indicator.
Parameters
packets The data container to write the frame to.
Returns
0 in case of success, an error code otherwise.
Definition at line 121 of file ProcPayload.cpp.
References devID, MSG_ID_REGISTER, and NW_OK.
Referenced by push().
uint8_t ProcPayload::pull (shared_ptr< Message_M2C > & input) virtual
Pulls input from chain of reception.
Receives data from successor and builds message for parent module. Returns status indicator.
Parameters
output The message to convert and send.
Returns
0 in case of success, an error code otherwise.
Implements FrontProcessor.
Definition at line 490 of file ProcPayload.cpp.
References FRAME_SIZE, FrameProcessor::getSuccessor(), MSG_ID_ACQUIRE, MSG_ID_COMMAND, NW_OK, unpackAcquiredData(), and unpackCommand().
uint8_t ProcPayload::push (shared_ptr< Message_M2C > output) virtual
Pushes output to chain of transmission..
Converts message 'output' into packets for sending and transmits them to successor. Returns status indicator.
Parameters
output The message to convert and send.
Returns
0 in case of success, an error code otherwise.
Implements FrontProcessor.
Definition at line 35 of file ProcPayload.cpp.
References MAX_ATTEMPT_PROC_PL, MSG_DATA_COMPLETE, MSG_EVENT, MSG_REGISTER, NW_OK, OK, packAcquiredData(), packEvent(), packRegister(), and FrameProcessor::transmit().
uint8_t ProcPayload::unpackAcquiredData (shared_ptr< M2C_DataAcquired > & data, shared_ptr< vector< uint8_t >> & packet, uint8_t *& begin, uint8_t *& end) private
Unpacks acquired data frame.
Unpacks frame for data acquisition and writes results to 'data'. Returns status indicator.
Parameters
data The target message
packet The packet to unpack.
begin Packet begin.
end packet end.
Returns
0 in case of success, an error code otherwise.
Definition at line 547 of file ProcPayload.cpp.
References ARG_ACQUIRED_DATA, and NW_OK.
Referenced by pull().
uint8_t ProcPayload::unpackCommand (shared_ptr< M2C_Command > & data, shared_ptr< vector< uint8_t >> & packet, uint8_t *& begin, uint8_t *& end) private
Unpacks command frame.
Unpacks frame for command and writes results to 'data'. Returns status indicator.
Parameters
data The target message
packet The packet to unpack.
begin Packet begin.
end packet end.
Returns
0 in case of success, an error code otherwise.
Definition at line 569 of file ProcPayload.cpp.
References ARG_COMMAND_TYPE, and NW_OK.
Referenced by pull().
Member Data Documentation
uint8_t ProcPayload::devID private
Definition at line 69 of file ProcPayload.h.
Referenced by packAcquiredData(), packEvent(), packRegister(), and ProcPayload().
timeval ProcPayload::step1 private
Definition at line 70 of file ProcPayload.h.
timeval ProcPayload::step2 private
Definition at line 70 of file ProcPayload.h.
The documentation for this class was generated from the following files:
src/nw-handling/ProcPayload.h
src/nw-handling/ProcPayload.cpp