AmberOnBoard: IOi2cBus Class Reference
IOi2cBus Class Reference
General class for i2c access.
#include <IOi2cBus.h>
Classes
class I2cBusDeleter
Public Member Functions
virtual uint8_t open (uint8_t type, bool force=false)
Opens bus.
virtual bool isOpen ()
Checks if bus is open.
virtual uint8_t setup ()
Bus setup.
virtual uint8_t reset ()
Bus reset.
virtual uint8_t close ()
Close bus.
uint8_t readBit (uint8_t devAddr, uint8_t regAddr, uint8_t bitNum, uint8_t *data)
uint8_t readBits (uint8_t devAddr, uint8_t regAddr, uint8_t bitStart, uint8_t length, uint8_t *data)
uint8_t readByte (uint8_t devAddr, uint8_t regAddr, uint8_t *data)
uint8_t readBytes (uint8_t devAddr, uint8_t regAddr, uint8_t length, uint8_t *data)
uint8_t writeBit (uint8_t devAddr, uint8_t regAddr, uint8_t bitNum, uint8_t data)
uint8_t writeBits (uint8_t devAddr, uint8_t regAddr, uint8_t bitStart, uint8_t length, uint8_t data)
uint8_t writeByte (uint8_t devAddr, uint8_t regAddr, uint8_t data)
uint8_t writeWord (uint8_t devAddr, uint8_t regAddr, uint16_t data)
uint8_t writeBytes (uint8_t devAddr, uint8_t regAddr, uint8_t length, uint8_t *data)
uint8_t writeWords (uint8_t devAddr, uint8_t regAddr, uint8_t length, uint16_t *data)
Public Member Functions inherited from IOparent
IOparent ()
Constructor.
virtual ~IOparent ()
Destructor.
void setActive (bool active)
Sets activity status.
bool isActive ()
Check instance activity.
uint8_t readSafe (string &input, uint8_t delim)
Safely reads from input.
uint8_t readOpen (string &input, uint8_t delim)
Opens input and reads from it.
uint8_t read (string &input, uint8_t delim)
Read from input.
uint8_t writeSafe (string output)
Safely writes string to output.
uint8_t write (string output)
Writes string to output.
uint8_t appendSafe (string output)
Safely appends string to output.
uint8_t appendOpen (string output)
Opens output in append mode and writes to it.
uint8_t append (string output)
Opens output in append mode and writes to it.
Static Public Member Functions
static shared_ptr< IOi2cBus > getInstance (string path)
Getter method for bus instances.
Protected Member Functions
virtual uint8_t getChar ()
Read byte.
virtual uint8_t putString (string &output)
Writes string to bus.
Private Member Functions
IOi2cBus (string path)
Constructor.
virtual ~IOi2cBus ()
Destructor.
uint8_t request (bool force=false, bool lock=false)
Requests a bus opening.
uint8_t release (bool lock=false)
Release bus.
Private Attributes
string path
int32_t fileDesc
mutex busMutex
Static Private Attributes
static unordered_map< string,
shared_ptr< IOi2cBus > > i2cDevices
Friends
class I2cBusDeleter
Detailed Description
General class for i2c access.
Gneral class for i2c access.
This class represents all i2c busses and offers methods for access. Original by Jeff Rowberg, modified by Daniel Wagenknecht
Author
Daniel Wagenknecht
Version
2014-12-22
Definition at line 68 of file IOi2cBus.h.
Constructor & Destructor Documentation
IOi2cBus::IOi2cBus (string path) private
Constructor.
Constructor of IOi2cBus instances, using 'path' as bus path. The constructor is private to avoid concurrent read / write operations on bus by letting the class manage access.
Parameters
path Path to device.
Definition at line 58 of file IOi2cBus.cpp.
References busMutex, fileDesc, and path.
IOi2cBus::~IOi2cBus () private virtual
Destructor.
Destructor of IOi2cBus instances.
Definition at line 72 of file IOi2cBus.cpp.
Member Function Documentation
uint8_t IOi2cBus::close () virtual
Close bus.
Closes the bus by calling release method. Returns status indicator
Returns
0 in case of success, an error code otherwise.
Implements IOparent.
Definition at line 187 of file IOi2cBus.cpp.
References release().
Referenced by release().
uint8_t IOi2cBus::getChar () protected virtual
Read byte.
Reads a single byte from bus and returns it. Note: I2C requires a specific protocol to get applied before any answer is coming from device.
Returns
Next character from bus.
Implements IOparent.
Definition at line 229 of file IOi2cBus.cpp.
References fileDesc, and IOparent::read().
shared_ptr< IOi2cBus > IOi2cBus::getInstance (string path) static
Getter method for bus instances.
Manages bus instance creation to avoid concurrent access.
Parameters
path Path to device.
Returns
IOi2cBus instance.
Definition at line 81 of file IOi2cBus.cpp.
References I2cBusDeleter, and i2cDevices.
Referenced by MPU6050::MPU6050(), and MPU6050::setPath().
bool IOi2cBus::isOpen () virtual
Checks if bus is open.
Returns whether the specified bus is already opened by this instance or not.
Returns
true if bus is open, false otherwise.
Implements IOparent.
Definition at line 163 of file IOi2cBus.cpp.
References fileDesc.
Referenced by readBytes(), release(), request(), writeBytes(), and writeWords().
uint8_t IOi2cBus::open (uint8_t type, bool force = false) virtual
Opens bus.
Opens the bus. If 'force' is true, the bus gets fully released before reopening it. Returns status indicator.
Parameters
type Ignored
force whether to reopen the bus or not.
Returns
0 in case of success, an error code otherwise.
Implements IOparent.
Definition at line 112 of file IOi2cBus.cpp.
References request().
Referenced by request().
uint8_t IOi2cBus::putString (string & output) protected virtual
Writes string to bus.
Writes all bytes of 'output' to the bus. Note: I2C requires a specific protocol to get applied for the device to get the output. Returns status indicator.
Returns
0 in case of success, an error code otherwise.
Implements IOparent.
Definition at line 248 of file IOi2cBus.cpp.
References fileDesc, IO_ERR_WRITE, IO_OK, and IOparent::write().
uint8_t IOi2cBus::readBit (uint8_t devAddr, uint8_t regAddr, uint8_t bitNum, uint8_t * data)
Read a single bit from an 8-bit device register.
Parameters
devAddr I2C slave device address
regAddr Register regAddr to read from
bitNum Bit position to read (0-7)
data Container for single bit value
Returns
Status indicator of read operation.
Definition at line 264 of file IOi2cBus.cpp.
References readByte().
uint8_t IOi2cBus::readBits (uint8_t devAddr, uint8_t regAddr, uint8_t bitStart, uint8_t length, uint8_t * data)
Read multiple bits from an 8-bit device register.
Parameters
devAddr I2C slave device address
regAddr Register regAddr to read from
bitStart First bit position to read (0-7)
length Number of bits to read (not more than 8)
data Container for right-aligned value (i.e. '101' read from any bitStart position will equal 0x05)
Returns
Status indicator of read operation.
Definition at line 279 of file IOi2cBus.cpp.
References readByte().
uint8_t IOi2cBus::readByte (uint8_t devAddr, uint8_t regAddr, uint8_t * data)
Read single byte from an 8-bit device register.
Parameters
devAddr I2C slave device address
regAddr Register regAddr to read from
data Container for byte value read from device
Returns
Status indicator of read operation.
Definition at line 301 of file IOi2cBus.cpp.
References readBytes().
Referenced by readBit(), readBits(), writeBit(), and writeBits().
uint8_t IOi2cBus::readBytes (uint8_t devAddr, uint8_t regAddr, uint8_t length, uint8_t * data)
Read multiple bytes from an 8-bit device register.
Parameters
devAddr I2C slave device address
regAddr First register regAddr to read from
length Number of bytes to read
data Buffer to store read data in
Returns
Status indicator of read operation.
Definition at line 312 of file IOi2cBus.cpp.
References busMutex, fileDesc, IO_ERR_READ, IO_ERR_SETUP, IO_ERR_WRITE, IO_OK, isOpen(), IOparent::read(), request(), and IOparent::write().
Referenced by readByte().
uint8_t IOi2cBus::release (bool lock = false) private
Release bus.
Releases the bus. If 'lock' is true, the bus access is thread safe. Returns status indicator
Returns
0 in case of success, an error code otherwise.
Definition at line 198 of file IOi2cBus.cpp.
References busMutex, close(), fileDesc, IO_ERR_CLOSE, IO_OK, and isOpen().
Referenced by close(), and request().
uint8_t IOi2cBus::request (bool force = false, bool lock = false) private
Requests a bus opening.
Requests a bus opening. If 'force' is true, the bus gets fully released before reopening it. If 'lock' is true, the bus access is thread safe. Returns status indicator.
Parameters
force Whether to reopen the bus or not.
lock Whether to open thread safe or not
Returns
0 in case of success, an error code otherwise.
Definition at line 126 of file IOi2cBus.cpp.
References busMutex, fileDesc, IO_ERR_OPEN, IO_OK, isOpen(), open(), path, release(), and IOparent::setActive().
Referenced by open(), readBytes(), writeBytes(), and writeWords().
uint8_t IOi2cBus::reset () virtual
Bus reset.
Does not affect i2c devices.
Implements IOparent.
Definition at line 178 of file IOi2cBus.cpp.
References IO_OK.
uint8_t IOi2cBus::setup () virtual
Bus setup.
Does not affect i2c devices.
Implements IOparent.
Definition at line 171 of file IOi2cBus.cpp.
References IO_OK.
uint8_t IOi2cBus::writeBit (uint8_t devAddr, uint8_t regAddr, uint8_t bitNum, uint8_t data)
write a single bit in an 8-bit device register.
Parameters
devAddr I2C slave device address
regAddr Register regAddr to write to
bitNum Bit position to write (0-7)
value New bit value to write
Returns
Status of operation (true = success)
Definition at line 356 of file IOi2cBus.cpp.
References readByte(), and writeByte().
uint8_t IOi2cBus::writeBits (uint8_t devAddr, uint8_t regAddr, uint8_t bitStart, uint8_t length, uint8_t data)
Write multiple bits in an 8-bit device register.
Parameters
devAddr I2C slave device address
regAddr Register regAddr to write to
bitStart First bit position to write (0-7)
length Number of bits to write (not more than 8)
data Right-aligned value to write
Returns
Status of operation (true = success)
Definition at line 371 of file IOi2cBus.cpp.
References IO_ERR_READ, readByte(), and writeByte().
uint8_t IOi2cBus::writeByte (uint8_t devAddr, uint8_t regAddr, uint8_t data)
Write single byte to an 8-bit device register.
Parameters
devAddr I2C slave device address
regAddr Register address to write to
data New byte value to write
Returns
Status of operation (true = success)
Definition at line 398 of file IOi2cBus.cpp.
References writeBytes().
Referenced by writeBit(), and writeBits().
uint8_t IOi2cBus::writeBytes (uint8_t devAddr, uint8_t regAddr, uint8_t length, uint8_t * data)
Write multiple bytes to an 8-bit device register.
Parameters
devAddr I2C slave device address
regAddr First register address to write to
length Number of bytes to write
data Buffer to copy new data from
Returns
Status of operation (true = success)
Definition at line 419 of file IOi2cBus.cpp.
References busMutex, fileDesc, IO_ERR_SETUP, IO_ERR_UNKNOWN, IO_ERR_WRITE, IO_OK, isOpen(), request(), and IOparent::write().
Referenced by writeByte().
uint8_t IOi2cBus::writeWord (uint8_t devAddr, uint8_t regAddr, uint16_t data)
Write single word to a 16-bit device register.
Parameters
devAddr I2C slave device address
regAddr Register address to write to
data New word value to write
Returns
Status of operation (true = success)
Definition at line 408 of file IOi2cBus.cpp.
References writeWords().
uint8_t IOi2cBus::writeWords (uint8_t devAddr, uint8_t regAddr, uint8_t length, uint16_t * data)
Write multiple words to a 16-bit device register.
Parameters
devAddr I2C slave device address
regAddr First register address to write to
length Number of words to write
data Buffer to copy new data from
Returns
Status of operation (true = success)
Definition at line 469 of file IOi2cBus.cpp.
References busMutex, fileDesc, IO_ERR_SETUP, IO_ERR_UNKNOWN, IO_ERR_WRITE, IO_OK, isOpen(), request(), and IOparent::write().
Referenced by writeWord().
Friends And Related Function Documentation
friend class I2cBusDeleter friend
Definition at line 105 of file IOi2cBus.h.
Referenced by getInstance().
Member Data Documentation
mutex IOi2cBus::busMutex private
Definition at line 116 of file IOi2cBus.h.
Referenced by IOi2cBus(), readBytes(), release(), request(), writeBytes(), and writeWords().
int32_t IOi2cBus::fileDesc private
Definition at line 115 of file IOi2cBus.h.
Referenced by getChar(), IOi2cBus(), isOpen(), putString(), readBytes(), release(), request(), writeBytes(), and writeWords().
unordered_map< string, shared_ptr< IOi2cBus > > IOi2cBus::i2cDevices static private
Definition at line 118 of file IOi2cBus.h.
Referenced by getInstance().
string IOi2cBus::path private
Definition at line 114 of file IOi2cBus.h.
Referenced by IOi2cBus(), and request().
The documentation for this class was generated from the following files:
src/io-handling/instances/IOi2cBus.h
src/io-handling/instances/IOi2cBus.cpp