AmberOnBoard: ValVectorUChar Class Reference
ValVectorUChar Class Reference
#include <Value.h>
Public Member Functions
ValVectorUChar ()
ValVectorUChar (shared_ptr< vector< unsigned char >> value)
virtual ~ValVectorUChar ()
shared_ptr< vector< unsigned
char > > getValue ()
void setValue (shared_ptr< vector< unsigned char >> value)
virtual shared_ptr< Value > clone ()
Public Member Functions inherited from Value
Value (int resType, bool initialized)
virtual ~Value ()=0
int getType ()
bool isInitialized ()
Private Member Functions
virtual shared_ptr
< ValVectorUChar > actualClone ()
Private Attributes
shared_ptr< vector< unsigned
char > > value
Additional Inherited Members
Protected Attributes inherited from Value
bool initialized
Detailed Description
Definition at line 99 of file Value.h.
Constructor & Destructor Documentation
ValVectorUChar::ValVectorUChar ()
Definition at line 149 of file Value.cpp.
References value.
Referenced by actualClone(), and clone().
ValVectorUChar::ValVectorUChar (shared_ptr< vector< unsigned char >> value)
Definition at line 153 of file Value.cpp.
References value.
ValVectorUChar::~ValVectorUChar () virtual
Definition at line 157 of file Value.cpp.
Member Function Documentation
shared_ptr< ValVectorUChar > ValVectorUChar::actualClone () private virtual
Definition at line 173 of file Value.cpp.
References ValVectorUChar().
Referenced by clone().
shared_ptr< Value > ValVectorUChar::clone () virtual
Implements Value.
Definition at line 169 of file Value.cpp.
References actualClone(), and ValVectorUChar().
shared_ptr< vector< unsigned char > > ValVectorUChar::getValue ()
Definition at line 160 of file Value.cpp.
References value.
void ValVectorUChar::setValue (shared_ptr< vector< unsigned char >> value)
Definition at line 164 of file Value.cpp.
References Value::initialized, and value.
Referenced by ModuleImgProcessing::processMsg(), and ValContainer::setValue().
Member Data Documentation
shared_ptr<vector<unsigned char> > ValVectorUChar::value private
Definition at line 109 of file Value.h.
Referenced by getValue(), setValue(), and ValVectorUChar().
The documentation for this class was generated from the following files:
src/Value.h
src/Value.cpp