AmberOnBoard: Module Class Reference
Module Class Reference abstract
Abstract parent class of application modules.
#include <Module.h>
Public Member Functions
Module ()
Constructor.
virtual ~Module ()
Destructor.
thread * createThread ()
int run ()
Run method of the modules main thread.
string getName ()
void update ()
Notify module about pending messages.
void terminate ()
Calls terminate on children.
bool isTerminating ()
Returns terminate status.
void addChild (shared_ptr< Child > child)
Adds a child to the list of executable children.
void deleteChild (shared_ptr< Child > child)
Deletes the child from the list of executable children.
void attachChildToMsg (shared_ptr< Child > observer, uint8_t type)
Attaches child to message type.
void detachChildFromMsg (shared_ptr< Child > observer, uint8_t type)
Detaches child from message type.
uint8_t getChildCount ()
Returns the number of children.
void runChild (uint8_t index)
Spawns a new thread on a modules child.
unordered_set< shared_ptr
< Child > >::iterator getChildrenBegin (uint8_t msgType)
Returns an iterator to first child listening to a message type.
unordered_set< shared_ptr
< Child > >::iterator getChildrenEnd (uint8_t msgType)
Returns an iterator to last child listening to a message type.
Public Member Functions inherited from Observer
Observer ()
virtual ~Observer ()
Protected Member Functions
bool msgAvailable ()
Checks if there are new messages available.
virtual uint8_t countMsgFromChildren ()=0
virtual uint8_t pollMsgFromChildren ()=0
uint8_t pollMsgFromHub ()
Polls oldest message from hub.
virtual shared_ptr< Message_M2M > processMsg (shared_ptr< Message_M2M >)=0
Private Attributes
shared_ptr< condition_variable > condition
shared_ptr< mutex > waitMutex
queue< shared_ptr< Msg > > sendBuf
vector< shared_ptr< Child > > children
unordered_set< shared_ptr
< thread > > childThreads
unordered_map< uint8_t,
unordered_set< shared_ptr
< Child > > > map_MsgType_Child
bool terminating
Detailed Description
Abstract parent class of application modules.
Abstract parent class of application modules. This class manages thread creation of the modules children and communication with them and the message hub. Implements observer. Is thread holder.
Author
Daniel Wagenknecht
Version
2014-10-31
Definition at line 26 of file Module.h.
Constructor & Destructor Documentation
Module::Module ()
Constructor.
Default Constructor of Module instances.
Definition at line 18 of file Module.cpp.
References terminating.
Module::~Module () virtual
Destructor.
Destructor of Module instances. Terminates and joins all child threads.
Definition at line 26 of file Module.cpp.
References children, and childThreads.
Member Function Documentation
void Module::addChild (shared_ptr< Child > child)
Adds a child to the list of executable children.
Adds the child specified by 'child' to the list of executable children.
Parameters
child The child to add.
Definition at line 121 of file Module.cpp.
References children.
Referenced by Initializer::processMsg(), Initializer::setUpEvtProc(), Initializer::setUpImgProc(), and Initializer::setUpIO().
void Module::attachChildToMsg (shared_ptr< Child > child, uint8_t type)
Attaches child to message type.
Attaches the child specified by 'child' to messages with id 'type'.
Parameters
child Child instance which gets attached to message.
type Message type to attach the child to.
Definition at line 46 of file Module.cpp.
References children, and map_MsgType_Child.
Referenced by ModuleNetworking::com_append(), ModuleEvent::pollMsgFromChildren(), and ModuleNetworking::pollMsgFromChildren().
virtual uint8_t Module::countMsgFromChildren () protected pure virtual
Implemented in Initializer, ModuleNetworking, ModuleImgProcessing, ModuleEvent, and ModuleIO.
Referenced by msgAvailable(), and run().
thread* Module::createThread ()
void Module::deleteChild (shared_ptr< Child > child)
Deletes the child from the list of executable children.
Deletes the child specified by 'child' from the list of executable children.
Parameters
child The child to delete.
Definition at line 132 of file Module.cpp.
References children.
void Module::detachChildFromMsg (shared_ptr< Child > child, uint8_t type)
Detaches child from message type.
Detaches the child specified by 'child' from messages with id 'type'.
Parameters
child Child instance which gets detached from message.
type Message type to detach the child from.
Definition at line 76 of file Module.cpp.
References map_MsgType_Child.
Referenced by ModuleNetworking::com_delete(), ModuleEvent::processMsg(), and ModuleNetworking::processMsg().
uint8_t Module::getChildCount ()
Returns the number of children.
Returns the number of children for this module.
Returns
Number of modules children.
Definition at line 296 of file Module.cpp.
References children.
Referenced by Initializer::processMsg(), and runChild().
unordered_set< shared_ptr< Child > >::iterator Module::getChildrenBegin (uint8_t msgType)
Returns an iterator to first child listening to a message type.
Returns an iterator to the first child in the list of children listening to message type 'msgType'.
Parameters
msgType Message type to get the first listening child for.
Returns
Iterator to the first child listening to given message type.
Definition at line 98 of file Module.cpp.
References map_MsgType_Child.
Referenced by ModuleEvent::processMsg(), and ModuleNetworking::processMsg().
unordered_set< shared_ptr< Child > >::iterator Module::getChildrenEnd (uint8_t msgType)
Returns an iterator to last child listening to a message type.
Returns an iterator to the last child in the list of children listening to message type 'msgType'.
Parameters
msgType Message type to get the last listening child for.
Returns
Iterator to the last child listening to given message type.
Definition at line 110 of file Module.cpp.
References map_MsgType_Child.
Referenced by ModuleEvent::processMsg(), and ModuleNetworking::processMsg().
string Module::getName ()
bool Module::isTerminating ()
Returns terminate status.
Returns whether this module is terminating or not.
Definition at line 176 of file Module.cpp.
References terminating.
Referenced by runChild().
bool Module::msgAvailable () protected
Checks if there are new messages available.
Checks if messages are pending on message hub or any of the children.
Returns
true if any message is pending for this module, false otherwise.
Definition at line 252 of file Module.cpp.
References countMsgFromChildren(), MsgHub::getInstance(), and MsgHub::getMsgCount().
Referenced by run().
virtual uint8_t Module::pollMsgFromChildren () protected pure virtual
Implemented in Initializer, ModuleNetworking, ModuleImgProcessing, ModuleEvent, and ModuleIO.
Referenced by run().
uint8_t Module::pollMsgFromHub () protected
Polls oldest message from hub.
Polls oldest message from hub, appends the answer (if any) to it and returns the number of processed messages.
Returns
1 if there was a message on hub, 0 otherwise.
Definition at line 270 of file Module.cpp.
References MsgHub::appendMsg(), MsgHub::getInstance(), MsgHub::getMsg(), and processMsg().
Referenced by run().
virtual shared_ptr<Message_M2M> Module::processMsg (shared_ptr< Message_M2M >) protected pure virtual
Implemented in Initializer, ModuleNetworking, ModuleImgProcessing, ModuleEvent, and ModuleIO.
Referenced by pollMsgFromHub().
int Module::run ()
Run method of the modules main thread.
Run method of this module. This method firstly starts all child processes. After that it checks in a while loop if new messages are pending on message hub or from children, until terminate was called. When the loop terminated, all children are also requested to terminate their execution.
Returns
0
Definition at line 189 of file Module.cpp.
References children, childThreads, condition, countMsgFromChildren(), MsgHub::getInstance(), msgAvailable(), pollMsgFromChildren(), pollMsgFromHub(), Child::run(), terminating, and waitMutex.
Referenced by Initializer::spawn().
void Module::runChild (uint8_t index)
Spawns a new thread on a modules child.
Spawns the child at index 'index' in the list of known children.
Definition at line 304 of file Module.cpp.
References children, childThreads, getChildCount(), isTerminating(), and Child::run().
Referenced by Initializer::processMsg().
void Module::terminate ()
Calls terminate on children.
Notifies children that a terminate request was sent.
Definition at line 163 of file Module.cpp.
References children, and terminating.
Referenced by ModuleIO::processMsg(), ModuleEvent::processMsg(), ModuleImgProcessing::processMsg(), ModuleNetworking::processMsg(), and Initializer::processMsg().
void Module::update () virtual
Notify module about pending messages.
Notifies module about new pending messages on message hub.
Implements Observer.
Definition at line 152 of file Module.cpp.
References condition.
Member Data Documentation
vector<shared_ptr<Child> > Module::children private
Definition at line 68 of file Module.h.
Referenced by addChild(), attachChildToMsg(), deleteChild(), getChildCount(), run(), runChild(), terminate(), and ~Module().
unordered_set<shared_ptr<thread> > Module::childThreads private
Definition at line 69 of file Module.h.
Referenced by run(), runChild(), and ~Module().
shared_ptr<condition_variable> Module::condition private
Definition at line 65 of file Module.h.
Referenced by run(), and update().
unordered_map<uint8_t, unordered_set<shared_ptr<Child> > > Module::map_MsgType_Child private
Definition at line 70 of file Module.h.
Referenced by attachChildToMsg(), detachChildFromMsg(), getChildrenBegin(), and getChildrenEnd().
queue<shared_ptr<Msg> > Module::sendBuf private
Definition at line 67 of file Module.h.
bool Module::terminating private
Definition at line 71 of file Module.h.
Referenced by isTerminating(), Module(), run(), and terminate().
shared_ptr<mutex> Module::waitMutex private
Definition at line 66 of file Module.h.
Referenced by run().
The documentation for this class was generated from the following files:
src/Module.h
src/Module.cpp