AmberOnBoard: Device Class Reference
Device Class Reference abstract
Abstract base class for deviecs.
#include <Device.h>
Public Member Functions
Device ()
Constructor.
virtual ~Device ()
Destructor.
virtual int run ()=0
void terminate ()
Sets termination flag.
bool isTerminating ()
Get termination value.
virtual void getValues (unordered_map< string, string > &values)=0
Static Protected Member Functions
static void addValue (unordered_map< string, string > &values, string key, string value)
Add value to results.
Private Attributes
bool terminating
Detailed Description
Abstract base class for deviecs.
Abstract base class for device instances.
Author
Daniel Wagenknecht
Version
2015-01-04
Definition at line 40 of file Device.h.
Constructor & Destructor Documentation
Device::Device ()
Constructor.
Default constructor of Device instances.
Definition at line 15 of file Device.cpp.
References terminating.
Device::~Device () virtual
Destructor.
Destructor of Device instances.
Definition at line 23 of file Device.cpp.
Member Function Documentation
void Device::addValue (unordered_map< string, string > & values, string key, string value) static protected
Add value to results.
Add 'value' with key 'key' to 'values'.
Definition at line 29 of file Device.cpp.
Referenced by OBDReader::getValues(), GpsAdafruit::getValues(), MPU6050::getValues(), OBDReader::run(), GpsAdafruit::run(), and MPU6050::run().
virtual void Device::getValues (unordered_map< string, string > & values) pure virtual
Implemented in MPU6050, GpsAdafruit, and OBDReader.
bool Device::isTerminating ()
Get termination value.
Returns whether device is terminating or not
Returns
true if terminate was called, false otherwise.
Definition at line 57 of file Device.cpp.
References terminating.
Referenced by OBDReader::run(), GpsAdafruit::run(), and MPU6050::run().
virtual int Device::run () pure virtual
Implemented in MPU6050, GpsAdafruit, and OBDReader.
Referenced by SensorIO::run().
void Device::terminate ()
Sets termination flag.
Sets termination flag.
Definition at line 47 of file Device.cpp.
References terminating.
Member Data Documentation
bool Device::terminating private
Definition at line 58 of file Device.h.
Referenced by Device(), isTerminating(), and terminate().
The documentation for this class was generated from the following files:
src/io-handling/Device.h
src/io-handling/Device.cpp