AmberOnBoard: OBDReader Class Reference
OBDReader Class Reference
#include <OBDReader.h>
Public Member Functions
OBDReader (string path, uint32_t baud)
Constructor for OBDReader class.
virtual ~OBDReader ()
Deconstructor if OBReader class.
virtual int run ()
virtual void getValues (unordered_map< string, string > &values)
uint8_t reset ()
Resets the ELM327 OBD-Interface.
uint8_t setup ()
Function to setting up the ELM327 interface.
int16_t getAdapter ()
To test the communication with the ELM327 USB Interface.
int16_t getSpeed ()
Gets the Speed of car in km/h.
int16_t getRPM ()
Gets the current RPM of car in turns/s.
int16_t getEngineLoad ()
Gets the current engine load of car in %.
int16_t getCoolantTemp ()
Gets the current coolant temperature of car in C°
int16_t getAirpressureInlet ()
Gets the current air pressure in the inlet of the car in kPa.
int16_t getInletAirTemp ()
Gets the current inlet air temperature of car in C°
int16_t getAirflow ()
Gets the current inlet airflow of car in grams/sec.
int16_t getEngineControlKM ()
Gets the driven distance in kilometer since the engine control light went on.
int32_t getFuelPressure ()
Gets the current fuel pressure in the inlet of the car in kPa.
int16_t getFuelLevel ()
Gets the current fuel level of the car in %.
uint8_t getOBDAnswer (string toCompare, string &input)
Gets the requested data from the OBD interface.
Public Member Functions inherited from Device
Device ()
Constructor.
virtual ~Device ()
Destructor.
void terminate ()
Sets termination flag.
bool isTerminating ()
Get termination value.
Private Attributes
IOserial device
unordered_map< string, string > values
mutex rw_mutex
Additional Inherited Members
Static Protected Member Functions inherited from Device
static void addValue (unordered_map< string, string > &values, string key, string value)
Add value to results.
Detailed Description
Definition at line 40 of file OBDReader.h.
Constructor & Destructor Documentation
OBDReader::OBDReader (string path, uint32_t baud)
Constructor for OBDReader class.
Creates a new OBDReader object an opens a serial port with the given paramters.
Parameters
path The path pf the serial device (ELM327 USB interface)
baud Transmission speed (baud rate of ELM328 USB interface)
Definition at line 25 of file OBDReader.cpp.
OBDReader::~OBDReader () virtual
Deconstructor if OBReader class.
Helps to close the serial port.
Definition at line 32 of file OBDReader.cpp.
References IOserial::close(), and device.
Member Function Documentation
int16_t OBDReader::getAdapter ()
To test the communication with the ELM327 USB Interface.
Sends a "getAdapter" command to the ELM327 interface. Interface answers with his name and his version. Function prints the name of the adapter.
Returns
0
Definition at line 291 of file OBDReader.cpp.
References IOparent::appendOpen(), device, OBD_DELIM, and IOparent::readOpen().
int16_t OBDReader::getAirflow ()
Gets the current inlet airflow of car in grams/sec.
Reads out the current inlet airflow of the car.
Returns
The current inlet airflow of the car in grams/sec
Definition at line 515 of file OBDReader.cpp.
References IOparent::appendOpen(), device, and getOBDAnswer().
Referenced by run().
int16_t OBDReader::getAirpressureInlet ()
Gets the current air pressure in the inlet of the car in kPa.
Reads out the current air pressure in the inlet of the car.
Returns
The current air pressure in the inlet of the car in kPa
Definition at line 449 of file OBDReader.cpp.
References IOparent::appendOpen(), device, and getOBDAnswer().
Referenced by run().
int16_t OBDReader::getCoolantTemp ()
Gets the current coolant temperature of car in C°
Reads out the current coolant temperature of the car.
Returns
The current coolant temperature of the car in C°
Definition at line 415 of file OBDReader.cpp.
References IOparent::appendOpen(), device, and getOBDAnswer().
Referenced by run().
int16_t OBDReader::getEngineControlKM ()
Gets the driven distance in kilometer since the engine control light went on.
Gets the driven distance in kilometer since the engine control light went on
Returns
The driven distance in kilometer since the engine control light went on
Definition at line 556 of file OBDReader.cpp.
References IOparent::appendOpen(), device, and getOBDAnswer().
Referenced by run().
int16_t OBDReader::getEngineLoad ()
Gets the current engine load of car in %.
Reads out the current engine load of the car.
Returns
The current engine load of the car in %
Definition at line 383 of file OBDReader.cpp.
References IOparent::appendOpen(), device, and getOBDAnswer().
Referenced by run().
int16_t OBDReader::getFuelLevel ()
Gets the current fuel level of the car in %.
Reads out the current fuel level of the car.
Returns
The current fuel level of the car in %
Definition at line 636 of file OBDReader.cpp.
References IOparent::appendOpen(), device, and getOBDAnswer().
Referenced by run().
int32_t OBDReader::getFuelPressure ()
Gets the current fuel pressure in the inlet of the car in kPa.
Reads out the current fuel pressure in the inlet of the car.
Returns
The current fuel pressure in the inlet of the car in kPa
Definition at line 596 of file OBDReader.cpp.
References IOparent::appendOpen(), device, and getOBDAnswer().
Referenced by run().
int16_t OBDReader::getInletAirTemp ()
Gets the current inlet air temperature of car in C°
Reads out the current inlet air temperature of the car.
Returns
The current inlet air temperature of the car in C°
Definition at line 480 of file OBDReader.cpp.
References IOparent::appendOpen(), device, and getOBDAnswer().
Referenced by run().
uint8_t OBDReader::getOBDAnswer (string toCompare, string & input)
Gets the requested data from the OBD interface.
Is called after a polling request of the software. It reads the requested data and cuts the carrier returns and new lines, so that the software gets the real requested data. Also catches errors from unplugging the interface from OBD port and errors from failed data transmissions. Returns index 5 if the data transmission between interface and odroid failed. Returns index 1 if the interface is unplugged. Returns index 0 if the correct OBD answer was received.
Parameters
toCompare String which the answer is compared to. To check if the received answer was correct
input reference var –> the requested OBD-Data is saved there
Returns
Returns an integer which represent the status of transmission
Definition at line 677 of file OBDReader.cpp.
References device, IO_ERR_READ, IO_ERR_UNKNOWN, IO_OK, OBD_DELIM, and IOparent::readOpen().
Referenced by getAirflow(), getAirpressureInlet(), getCoolantTemp(), getEngineControlKM(), getEngineLoad(), getFuelLevel(), getFuelPressure(), getInletAirTemp(), getRPM(), and getSpeed().
int16_t OBDReader::getRPM ()
Gets the current RPM of car in turns/s.
Reads out the current RPM of the car.
Returns
The current RPM of the car in turn/s
Definition at line 342 of file OBDReader.cpp.
References IOparent::appendOpen(), device, and getOBDAnswer().
Referenced by run().
int16_t OBDReader::getSpeed ()
Gets the Speed of car in km/h.
Reads out the current speed of the car.
Returns
The speed of the car in km/h
Definition at line 308 of file OBDReader.cpp.
References IOparent::appendOpen(), device, and getOBDAnswer().
Referenced by run().
void OBDReader::getValues (unordered_map< string, string > & values) virtual
Implements Device.
Definition at line 88 of file OBDReader.cpp.
References Device::addValue(), OBD_AIR_FLOW, OBD_COOL_TEMP, OBD_ENG_KM, OBD_ENG_LOAD, OBD_FUEL_LVL, OBD_FUEL_PRESS, OBD_INLET_PRESS, OBD_INLET_TEMP, OBD_RPM, OBD_SPEED, and rw_mutex.
uint8_t OBDReader::reset ()
Resets the ELM327 OBD-Interface.
Reset command is send to interface and reads the reset answers of the interface from serial port. During that the function is checking if the answers of the interface are correct. If the reset of the interface where successful the index 0 is returned. If not the index 1 is returned.
Returns
An integer with the status of the reset
Definition at line 154 of file OBDReader.cpp.
References IOparent::appendOpen(), device, IO_ERR_UNKNOWN, IO_OK, OBD_DELIM, OBD_RESET, and IOparent::readOpen().
Referenced by setup().
int OBDReader::run () virtual
Implements Device.
Definition at line 37 of file OBDReader.cpp.
References Device::addValue(), device, getAirflow(), getAirpressureInlet(), getCoolantTemp(), getEngineControlKM(), getEngineLoad(), getFuelLevel(), getFuelPressure(), getInletAirTemp(), getRPM(), getSpeed(), IOparent::isActive(), Device::isTerminating(), OBD_AIR_FLOW, OBD_COOL_TEMP, OBD_ENG_KM, OBD_ENG_LOAD, OBD_FUEL_LVL, OBD_FUEL_PRESS, OBD_INLET_PRESS, OBD_INLET_TEMP, OBD_RPM, OBD_SPEED, rw_mutex, SLEEP_DURATION, and values.
uint8_t OBDReader::setup ()
Function to setting up the ELM327 interface.
Setting up the interface for parsing the received data. Therefore the echo, the OBD-Header, the line feeder and the blanks between the received data are disabled. In some cases there are problems with disabling the echo and some additional outputs. Therefore the disable echo function catches those additional outputs. Small delays between the single setup steps improve the reliability of the setup.
Returns
An integer with the status of the setup
Definition at line 192 of file OBDReader.cpp.
References IOparent::appendOpen(), device, IO_OK, OBD_BLANKS_OFF, OBD_DELIM, OBD_ECHO_OFF, OBD_HEADER_OFF, OBD_LINEFEED_OFF, IOparent::readOpen(), and reset().
Member Data Documentation
IOserial OBDReader::device private
Definition at line 73 of file OBDReader.h.
Referenced by getAdapter(), getAirflow(), getAirpressureInlet(), getCoolantTemp(), getEngineControlKM(), getEngineLoad(), getFuelLevel(), getFuelPressure(), getInletAirTemp(), getOBDAnswer(), getRPM(), getSpeed(), reset(), run(), setup(), and ~OBDReader().
mutex OBDReader::rw_mutex private
Definition at line 79 of file OBDReader.h.
Referenced by getValues(), and run().
unordered_map<string, string> OBDReader::values private
Definition at line 76 of file OBDReader.h.
Referenced by run().
The documentation for this class was generated from the following files:
src/io-handling/OBDReader.h
src/io-handling/OBDReader.cpp